### ISSUE TITLE
HTML report does not work if there are outputs outside the recipe folder

### ISSUE THREAD

**Issue by jvegasbsc** [ESMValGroup/ESMValCore#1154]
If one or more the outputs is not stored inside the recipe folder, the HTML report fails to generate and the application crashes. 

There are multiple things to discuss:

- Do we want to support those cases in the report?
- If not, how do we manage the error? Two main options: downgrade it to a warning (at the end, the recipe ran well) or allow users to disable report generation through a CL argument or similar

I encountered that behaviour in ESMValGroup/ESMValTool#2184. See a sample of the error:

```
Traceback (most recent call last):
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/_main.py", line 433, in run
    fire.Fire(ESMValTool())
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/_main.py", line 410, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/_main.py", line 105, in process_recipe
    recipe.write_html_summary()
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/_recipe.py", line 1446, in write_html_summary
    output.write_html()
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/experimental/recipe_output.py", line 145, in write_html
    html_dump = self.render(template=template)
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/experimental/recipe_output.py", line 161, in render
    rendered = template.render(
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/experimental/templates/recipe_output_page.j2", line 12, in top-level template code
    {% include 'RecipeOutput.j2' %}
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/experimental/templates/RecipeOutput.j2", line 3, in top-level template code
    {% include 'TaskOutput.j2' %}
  File "/home/Earth/jvegas/git/ESMValCore/esmvalcore/experimental/templates/TaskOutput.j2", line 9, in top-level template code
    <img width='80%' src='{{ file.path.relative_to(session.session_dir) }}' alt='{{ file.caption }}'/>
  File "/home/Earth/jvegas/.conda/envs/esmvaltool/lib/python3.9/pathlib.py", line 928, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/home/Earth/jvegas/plots/EC-Earth3-CC/piControl/seaIce/sivol/monclimarctic_sivol_EC-Earth3-CC_SImon_piControl_r1i1p1f1.png' is not in the subpath of '/esarchive/scratch/jvegas/recipe_monitor_20210531_102719' OR one path is relative and the other is absolute.
```

**Comment by stefsmeets** [comment]
I'm not convinced this is a bug in esmvalcore or the html renderer. All output is normally stored in the `plot_dir` or `work_dir`. The underlying issue to me is that the recipe you are developing tries to write outside the recipe output directory. What problem are you trying to solve by writing outside the designated directories?

**Comment by zklaus** [comment]
@stefsmeets, I understand your reluctance and I tend to agree that recipes should possibly be confined in some way.

But I also understand @jvegasbsc use case, which is combining information from different runs of ESMValTool for monitoring purposes and I think that the report generator is not the place to enforce a confinement policy.

@stefsmeets, could you please adapt the report generator so that it can work with absolute paths as well and open an issue or a discussion on the wider point of whether recipes should be allowed to behave in this way?

**Comment by stefsmeets** [comment]
> @stefsmeets, could you please adapt the report generator so that it can work with absolute paths as well and open an issue or a discussion on the wider point of whether recipes should be allowed to behave in this way?

I don't see how this is possible with the current design. It will break the purpose of having a self-contained results directory that can be moved around. The paths being relative is especially important if they are to be hosted online, which was one of the driving points for developing this.

1. Paths are absolute, this will fix @jvegasbsc workflow. Results directory cannot be moved/shared/hosted online.
2. Paths are relative, results directory can be moved/shared/hosted online easily. @jvegasbsc may need to adjust his workflow. The paths are easily accessible through the provenance api. @jvegasbsc , would it be possible to adapt your workflow to move the data after they have been generated?
3. Of course it is possible to develop some sort of work-around that will fix this particular use-case. My preference would be to wrap the html generation in a try/except block, and log the error message.

**Comment by jvegasbsc** [comment]
I vote for option 3 or even make it a bit more strict with a CL flag. Users should not store anything outside the recipe unless they know what they are doing

**Comment by bouweandela** [comment]
I'm not convinced yet that writing outside the recipe folder is a good idea. @jvegasbsc Could you explain in a bit more detail why this is needed? Why is it not possible to move the output to the desired location after the ESMValCore run?

**Comment by zklaus** [comment]
I think @jvegasbsc is working on monitoring, that is running the model for a so-called leg, say one year, then running ESMValTool to produce a plot of, for example, global mean temperature, while the model is already running the next year. After that, you want to update the plot with the new data, which only works if you have some form of permanence across different ESMValTool runs.

Regardless, I think if we want to enforce confinement to the recipe directory, that is not the job of the report generator, or what do you think?

**Comment by bouweandela** [comment]
I think that writing outside of the advertised output file or directory is very poor behavior for any program.

> After that, you want to update the plot with the new data, which only works if you have some form of permanence across different ESMValTool runs.

The permanence can be obtained by specifying an extra input data directory or directories with previous results that can be used by the diagnostic script, e.g. in the recipe or using the `auxiliary_data_dir` option in config-user.yml. This was previously discussed at an ESMValTool workshop, see. e.g. https://github.com/ESMValGroup/ESMValTool/issues/601#issuecomment-499455232.

**Comment by bouweandela** [comment]
Reading the summary from that discussion again, that is not quite what I meant. I would just use the data specified in the extra input paths combined with the data from the current run to generate the plots.

**Comment by bouweandela** [comment]
> Regardless, I think if we want to enforce confinement to the recipe directory, that is not the job of the report generator, or what do you think?

Not necessarily, but I think it should be fine to assume that the output is written to the output directory anywhere in the code, because it's rather surprising to users if you start writing to other places too.

**Comment by bouweandela** [comment]
Anyway, I did not mean to say this feature is not necessary, just that I'm not convinced that it is needed yet. Arguments as to why it is needed are very welcome!

**Comment by zklaus** [comment]
I guess right now the pressing question is whether this should be considered a bug that needs fixing for 2.3.0 or not.

@jvegasbsc, will it make 2.3.0 much more useful for you if this is in? Or do you depend on other new additions to the core that would be missing anyways? Could you work around this in a manner as described by @bouweandela, or perhaps with a strategically placed symbolic link?

**Comment by zklaus** [comment]
There doesn't seem an appetite to push this through before the release. I'll delay it to 2.4.0 since it is arguably not a bug, but a feature. We can then decide how to proceed in the long run.

**Comment by senesis** [comment]
The basic issue here is in my mind related to a topic discussed in the context of defining a standard interface (see https://github.com/IsEnesEval/diagstandards/pull/1#discussion_r748047611)
Namely, the workflow which calls ESMValTool for invoking a given script has no way to know the output file paths, nor the output directory path, because **no convention exists for that**; so, it cannot proceed with the housekeeping after ESMValTool run; so it has to do it during th erun (towards the end), but cannot do it after the HTML report phase; which generates the issue.

**Comment by bouweandela** [comment]
> Namely, the workflow which calls ESMValTool for invoking a given script has no way to know the output file paths, nor the output directory path, because no convention exists for that

There is a convention for the output directory paths, it is documented [here](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/interfaces.html#information-provided-by-esmvalcore-to-the-diagnostic-script):

- `run_dir` use this for storing temporary files
- `work_dir` use this for storing NetCDF files containing the data used to make a plot
- `plot_dir` use this for storing plots

The paths are provided by the esmvalcore to diagnostic interface YAML file and all diagnostics currently in the ESMValTool package follow this convention.

**Comment by senesis** [comment]
> There is a convention for the output directory paths, it is documented [here](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/interfaces.html#information-provided-by-esmvalcore-to-the-diagnostic-script):

I know that, but this is not enough : each `plot_dir` can contain multiple graph files, and there is no convention by which the script could declare which is what

**Comment by zklaus** [comment]
@sloosvel, since you are taking over most things from @jvegreg, could you let us know if this issue is still relevant?

**Comment by sloosvel** [comment]
I would say no: https://github.com/ESMValGroup/ESMValTool/pull/2184#issuecomment-977955838
