### ISSUE TITLE
 Hard to understand error about missing CMOR tables when a directory cordex is present in current working directory

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1257]
If there is a directory called `cordex` in the current working directory, the `esmvaltool` command crashes with the following stack trace:
```
$ esmvaltool run examples/recipe_python.yml
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_main.py", line 432, in run
    fire.Fire(ESMValTool())
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_main.py", line 352, in run
    from ._config import (
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_config/__init__.py", line 2, in <module>
    from ._config import (
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_config/_config.py", line 13, in <module>
    from esmvalcore.cmor.table import CMOR_TABLES, read_cmor_tables
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/cmor/table.py", line 889, in <module>
    read_cmor_tables()
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/cmor/table.py", line 63, in read_cmor_tables
    CMOR_TABLES[table] = _read_table(cfg_developer, table, install_dir,
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/cmor/table.py", line 85, in _read_table
    return CMIP5Info(table_path,
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/cmor/table.py", line 639, in __init__
    raise OSError(errno.ENOTDIR, "CMOR tables path is not a directory",
NotADirectoryError: [Errno 20] CMOR tables path is not a directory: 'cordex/Tables'
```

Steps to reproduce:
```bash
mkdir cordex
esmvaltool run examples/recipe_python.yml
```

This problem looks the same as #316 but then for a directory called `cordex` instead of `cmip5`.

**Comment by bouweandela** [comment]
While it would be desirable to fix this, it appears not to have a high enough priority since nobody worked on fixing this over the past few years. If anyone is interested in working on this, please feel free to reopen.
