### ISSUE TITLE
If `extract_levels` is run before `area_statistics` (or prob any other preprocessor needing `cell_measure`) the cell measure vanishes

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1331]
**Recipe in question**

```yaml
diagnostics:
  diag_timeseries_3:
    scripts: Null
    variables:
      chl_ts_hist:
        additional_datasets:
          - {dataset: CanESM5, end_year: 1852, ensemble: r17i1p1f1, exp: historical,grid: gn, mip: Omon, project: CMIP6, start_year: 1850}
        end_year: 1852
        exp: historical
        grid: gn
        mip: Omon
        preprocessor: prep_regional_ts_3d_surface
        project: CMIP6
        short_name: chl
        start_year: 1850
documentation:
  authors: [demora_lee]
  description: "Template recipe to produce a generic plot of temperature for the Ascension\
    \ Islands.\n"
  maintainer: [demora_lee]
  projects: [ukesm]
  references: [demora2018gmd]
preprocessors:
  prep_regional_ts_3d_surface: # For regional fields
    custom_order: true
    #extract_levels:
    #    scheme: linear
    #    levels: [0.,]
    area_statistics:
      operator: mean
      fx_variables:
        - {activity: CMIP,  grid: gn, mip: Ofx, short_name: areacello, exp: '1pctCO2', ensemble: 'r1i1p1f1'}
```

(toggle the `extract_levels` preprocessor on or off)

**Behaviour**

- without `extract_levels`: all goes smoothly:
```
2021-09-23 16:02:04,173 UTC [3517] DEBUG   esmvalcore.preprocessor._ancillary_vars:104 Added areacello as cell measure in cube of chl.
2021-09-23 16:02:04,173 UTC [3517] DEBUG   esmvalcore.preprocessor:295 Running preprocessor step area_statistics
2021-09-23 16:02:04,183 UTC [3517] DEBUG   esmvalcore.preprocessor:285 Running area_statistics(mass_concentration_of_phytoplankton_expressed_as_chlorophyll_in_sea_water / (kg m-3) (time: 36; depth: 45; cell index along second dimension: 291; cell index along first dimension: 360)
...
021-09-23 16:02:26,923 UTC [2951] INFO    esmvalcore._main:417 Run was successful
```
- with `extract_levels`: guff hits the fan:
```
2021-09-23 16:15:00,164 UTC [6489] DEBUG   esmvalcore.preprocessor._ancillary_vars:104 Added areacello as cell measure in cube of chl.
2021-09-23 16:15:00,164 UTC [6489] DEBUG   esmvalcore.preprocessor:295 Running preprocessor step extract_levels
2021-09-23 16:15:00,180 UTC [6489] DEBUG   esmvalcore.preprocessor:285 Running extract_levels(mass_concentration_of_phytoplankton_expressed_as_chlorophyll_in_sea_water / (kg m-3) (time: 36; depth: 45; cell index along second dimension: 291; cell index along first dimension: 360)
...
2021-09-23 16:15:21,129 UTC [6489] DEBUG   esmvalcore.preprocessor:295 Running preprocessor step area_statistics
2021-09-23 16:15:21,134 UTC [6489] DEBUG   esmvalcore.preprocessor:285 Running area_statistics(mass_concentration_of_phytoplankton_expressed_as_chlorophyll_in_sea_water / (kg m-3) (time: 36; cell index along second dimension: 291; cell index along first dimension: 360)
...
2021-09-23 16:15:21,136 UTC [6489] INFO    esmvalcore.preprocessor._area:237 Cell measure "cell_area" not found in cube mass_concentration_of_phytoplankton_expressed_as_chlorophyll_in_sea_water / (kg m-3) (time: 36; cell index along second dimension: 291; cell index along first dimension: 360). Check fx_file availability.
2021-09-23 16:15:21,136 UTC [6489] INFO    esmvalcore.preprocessor._area:241 Attempting to calculate grid cell area...
2021-09-23 16:15:21,136 UTC [6489] ERROR   esmvalcore.preprocessor._area:255 fx_file needed to calculate grid cell area for irregular grids.
2021-09-23 16:15:21,137 UTC [6489] ERROR   esmvalcore.preprocessor:289 Failed to run area_statistics(mass_concentration_of_phytoplankton_expressed_as_chlorophyll_in_sea_water / (kg m-3) (time: 36; cell index along second dimension: 291; cell index along first dimension: 360)
```

**Most probable solution**

Inspect the cube attrs saving after select levels has run, bet you my boots the `cell_measure` added before gets evicted for not paying rent :grin:

**Comment by sloosvel** [comment]
Could you test it with https://github.com/ESMValGroup/ESMValCore/pull/1269 ?

**Comment by zklaus** [comment]
Duplicate of #1189 ?

**Comment by valeriupredoi** [comment]
> Duplicate of #1189 ?

it most certainly looks to be @zklaus - cheers, completely forgot about that! Thanks @sloosvel - I'll run that branch tomorrow just to make sure this is not some corner case and will close this. @ledm it's very useful to search for open issues/PR's about certain stuff if you have issues with them (eg here fx cell measures and extract levels) - you'll know what's up with the fail w/o having to do black box testing (like I did here, me being a dummy too, and should have looked for exiting issues) :beer:

**Comment by valeriupredoi** [comment]
hi @sloosvel I just tested with #1269 and things are looking up but I get this dimensional mismatch:
```
2021-09-24 10:53:07,917 UTC [30216] ERROR   Program terminated abnormally, see stack trace below for more information:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 754, in _run_task
    output_files = task.run()
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 252, in run
    self.output_files = self._run(input_files)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 482, in _run
    product.apply(step, self.debug)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 351, in apply
    self.cubes = preprocess(self.cubes, step, **self.settings[step])
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 298, in preprocess
    result.append(_run_preproc_function(function, item, settings))
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 281, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_regrid.py", line 759, in extract_levels
    _preserve_fx_vars(cube, result)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_regrid.py", line 659, in _preserve_fx_vars
    result.add_cell_measure(measure, measure_dims)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/cube.py", line 1187, in add_cell_measure
    data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/cube.py", line 1120, in _check_multi_dim_metadata
    raise ValueError(
ValueError: Unequal lengths. Cube dimension 2 => 360; metadata 'cell_area' dimension 0 => 291.
```
If you think we should move the discussion to #1189 I can move the OP and this comment there :+1:

**Comment by sloosvel** [comment]
Ok, thanks for trying. I'll take a look.

**Comment by sloosvel** [comment]
It did work fine for me though 

[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/7243001/main_log_debug.txt)
[main_log.txt](https://github.com/ESMValGroup/ESMValCore/files/7243003/main_log.txt)

**Comment by valeriupredoi** [comment]
hi @sloosvel cheers much for looking into this; unfortunately, with the latest Core at `dev_preserve_fx` and `main` for Tool (Tool don't really matter anyway) the error is perfectly replicated see 
[debug_recipe_Lee.txt](https://github.com/ESMValGroup/ESMValCore/files/7243180/debug_recipe_Lee.txt)

It's very possible you've not committed/pushed changes in your local devel work, can you pls make sure you've pushed everything to remote? :beer:

**Comment by valeriupredoi** [comment]
note that I am using a slightly older iris:
```
(esmvaltool-stock) [valeriu@sci2 esmvalcore]$ conda list iris
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock:
#
# Name                    Version                   Build  Channel
iris                      3.0.3            py39hf3d152e_0    conda-forge
```
but if iris is a problem then we're in a pickle since we need to support older versions too. I will try upgrade with the latest 3.1 and see if that does it

**Comment by sloosvel** [comment]
I ran this on jasmin and I don't develop there, so my branch is updated and it must be due to something else... Let's see if I find out.

**Comment by valeriupredoi** [comment]
strange...I updated to 3.1 and still getting the exact same issue, here's the recipe reposted just so we are on the very same page:
```yaml
diagnostics:
  diag_timeseries_3:
    scripts: Null
    variables:
      chl_ts_hist:
        additional_datasets:
          - {dataset: CanESM5, end_year: 1852, ensemble: r17i1p1f1, exp: historical,grid: gn, mip: Omon, project: CMIP6, start_year: 1850}
        end_year: 1852
        exp: historical
        grid: gn
        mip: Omon
        preprocessor: prep_regional_ts_3d_surface
        project: CMIP6
        short_name: chl
        start_year: 1850
documentation:
  authors: [demora_lee]
  description: "Template recipe to produce a generic plot of temperature for the Ascension\
    \ Islands.\n"
  maintainer: [demora_lee]
  projects: [ukesm]
  references: [demora2018gmd]
preprocessors:
  prep_regional_ts_3d_surface: # For regional fields
    custom_order: true
    extract_levels:
        scheme: linear
        levels: [0.,]
    area_statistics:
      operator: mean
      fx_variables:
        - {activity: CMIP,  grid: gn, mip: Ofx, short_name: areacello, exp: '1pctCO2', ensemble: 'r1i1p1f1'}
 ```

**Comment by valeriupredoi** [comment]
@ledm since this is your recipe, could you please test too, mate :beer:

**Comment by sloosvel** [comment]
It's something that works with ESMValTool 2.2 but not with ESMValTool 2.3.1

**Comment by valeriupredoi** [comment]
cheers Saskia, am gonna look at it in more detail now myself - pretty strange to say the least :grin:

**Comment by valeriupredoi** [comment]
OK `_preserve_fx_vars` from `_regrid.py` is not present in v2.2.0 so it's only normal it works with 2.2.0 since the treatment of cell measures is not happening at the vertical levs extraction point in the older version

**Comment by sloosvel** [comment]
Ok, this is happening because in this particular case, the resulting cube loses depth as a dimension. I did not consider that case in the PR. I'll change it to include it.

**Comment by valeriupredoi** [comment]
cheers Saskia! Let me know if I can help :beer:

**Comment by sloosvel** [comment]
It should work now.

**Comment by valeriupredoi** [comment]
It does indeed, many thanks @sloosvel (don't close this now please, I'll add it as being closed by #1269 to have a correct record)

**Comment by valeriupredoi** [comment]
valiantly fixed by #1269 :checkered_flag:
