### ISSUE TITLE
Recipes without a title do not run

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1338]
**Describe the bug**
It seems that recipes without a title can not be run since #1332 has been merged. Running : `esmvaltool run examples/recipe_python.yml` returns:
```bash
Traceback (most recent call last):
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_main.py", line 438, in run
    fire.Fire(ESMValTool())
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_main.py", line 415, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_main.py", line 101, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_recipe.py", line 61, in read_recipe_file
    check.recipe_with_schema(filename)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_recipe_checks.py", line 63, in recipe_with_schema
    yamale.validate(schema, recipe, strict=False)
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.9/site-packages/yamale/yamale.py", line 43, in validate
    raise YamaleError(results)
yamale.yamale_error.YamaleError: Error validating data '/mnt/lustre01/pf/b/b309192/ESMValTool/esmvaltool/recipes/examples/recipe_python.yml' with schema '/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/recipe_schema.yml'
        documentation.title: Required field missing
```

I'm using the latest versions of the Tool and the Core which I reinstalled. Am I understanding correctly that any recipe without a title cannot be run because of this [check](https://github.com/ESMValGroup/ESMValCore/blob/37e7ecd5d3fdd7bcd58210240616f5b88174a68a/esmvalcore/recipe_schema.yml#L14)? Note that no recipe in the `examples` directory has a title, so it seems that none can be run at the moment.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

**Comment by bouweandela** [comment]
Yes, this is correct, see discussion in #1319. We will need to add the [titles from the documentation](https://docs.esmvaltool.org/en/latest/recipes/index.html) before making the release. Would it be OK to transfer this issue to ESMValTool?
