### ISSUE TITLE
Issue in multimodel cube merge surfaced by running `recipe_preprocessor_test.yml`

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1339]
```
2021-10-01 10:35:40,900 UTC [16801] ERROR   Failed to run multi_model_statistics({<esmvalcore.preprocessor.PreprocessorFile object at 0x7f95f92d1190>, <esmvalcore.preprocessor.PreprocessorFile object at 0x7f95f92d1340>, <esmvalcore.preprocessor.PreprocessorFile object at 0x7f95f92b2d60>, <esmvalcore.preprocessor.PreprocessorFile object at 0x7f95f92d1070>}, {'span': 'overlap', 'statistics': ['mean', 'median'], 'output_products': {'mean': <esmvalcore.preprocessor.PreprocessorFile object at 0x7f95f92b2e80>, 'median': <esmvalcore.preprocessor.PreprocessorFile object at 0x7f95f92b2eb0>}})
2021-10-01 10:35:41,867 UTC [16766] INFO    Maximum memory used (estimate): 6.2 GB
2021-10-01 10:35:41,868 UTC [16766] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2021-10-01 10:35:41,870 UTC [16766] ERROR   Program terminated abnormally, see stack trace below for more information:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 747, in _run_task
    output_files = task.run()
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 252, in run
    self.output_files = self._run(input_files)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 481, in _run
    self.products = _apply_multimodel(self.products, step,
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 422, in _apply_multimodel
    result = preprocess(products - exclude, step, **settings)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 299, in preprocess
    result.append(_run_preproc_function(function, items, settings))
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 285, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 414, in multi_model_statistics
    return _multiproduct_statistics(
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 325, in _multiproduct_statistics
    statistics_cubes = _multicube_statistics(cubes=cubes,
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 305, in _multicube_statistics
    result_cube = _compute_eager(aligned_cubes,
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 250, in _compute_eager
    combined_slice = _combine(single_model_slices)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 220, in _combine
    merged_cube = cubes.merge_cube()
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/cube.py", line 402, in merge_cube
    proto_cube.register(cube, error_on_mismatch=True)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/_merge.py", line 1361, in register
    match = coord_payload.match_signature(
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/_merge.py", line 284, in match_signature
    raise iris.exceptions.MergeError(msgs)
iris.exceptions.MergeError: failed to merge into a single cube.
  Coordinates in cube.dim_coords differ: air_pressure.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/valeriu/esmvalcore/esmvalcore/_main.py", line 438, in run
    fire.Fire(ESMValTool())
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_main.py", line 415, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_main.py", line 105, in process_recipe
    recipe.run()
  File "/home/users/valeriu/esmvalcore/esmvalcore/_recipe.py", line 1515, in run
    self.tasks.run(max_parallel_tasks=self._cfg['max_parallel_tasks'])
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 669, in run
    self._run_parallel(max_parallel_tasks)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 712, in _run_parallel
    _copy_results(task, running[task])
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 735, in _copy_results
    task.output_files, updated_products = future.get()
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 747, in _run_task
    output_files = task.run()
  File "/home/users/valeriu/esmvalcore/esmvalcore/_task.py", line 252, in run
    self.output_files = self._run(input_files)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 481, in _run
    self.products = _apply_multimodel(self.products, step,
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 422, in _apply_multimodel
    result = preprocess(products - exclude, step, **settings)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 299, in preprocess
    result.append(_run_preproc_function(function, items, settings))
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/__init__.py", line 285, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 414, in multi_model_statistics
    return _multiproduct_statistics(
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 325, in _multiproduct_statistics
    statistics_cubes = _multicube_statistics(cubes=cubes,
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 305, in _multicube_statistics
    result_cube = _compute_eager(aligned_cubes,
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 250, in _compute_eager
    combined_slice = _combine(single_model_slices)
  File "/home/users/valeriu/esmvalcore/esmvalcore/preprocessor/_multimodel.py", line 220, in _combine
    merged_cube = cubes.merge_cube()
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/cube.py", line 402, in merge_cube
    proto_cube.register(cube, error_on_mismatch=True)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/_merge.py", line 1361, in register
    match = coord_payload.match_signature(
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock/lib/python3.9/site-packages/iris/_merge.py", line 284, in match_signature
    raise iris.exceptions.MergeError(msgs)
iris.exceptions.MergeError: failed to merge into a single cube.
  Coordinates in cube.dim_coords differ: air_pressure.
2021-10-01 10:35:41,885 UTC [16766] INFO
```
iris latest:
```
(esmvaltool-stock) [valeriu@sci2 esmvaltool_var_test]$ conda list iris
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock:
#
# Name                    Version                   Build  Channel
iris                      3.1.0            py39hf3d152e_1    conda-forge
```

**Comment by bouweandela** [comment]
Without knowing at least the recipe and main_log_debug.txt it will be very hard to find out what is going wrong here.

**Comment by valeriupredoi** [comment]
read the issue title one more time :wink:

**Comment by zklaus** [comment]
This is because of ESMValGroup/ESMValTool#2241. Basically our ERA-Interim cmorizer adds bounds that are not expected or provided in the CMIP data. I tend to agree with CMIP as discussed in that issue.

Perhaps you can help to drive the discussion in ESMValGroup/ESMValTool#2241 so we get a clearer picture where to go there?

**Comment by valeriupredoi** [comment]
spot on Klaus! Will go there :beer:

**Comment by bouweandela** [comment]
I'm not sure i agree with that conclusion, rather i suspect this is a result of #414: the era interim data has bounds, the other models are interpolated to the same levels, but without bounds and then the multimodel statistics preprocessor function fails to combine the vertical into a single coordinate.

**Comment by zklaus** [comment]
@bouweandela, to clarify: Do you think ESMValGroup/ESMValTool#2241 is wrong or that it doesn't apply here?

**Comment by bouweandela** [comment]
I think it doesn't apply here

**Comment by bouweandela** [comment]
In this particular case, i think the recipe should just be updated so era interim is excluded from multimodel statistics instead of ncep which isn't even in the recipe. It doesn't make much sense to include the 'observation' in a multi model comparison.

**Comment by zklaus** [comment]
NCEP actually does appear as an additional dataset in the diagnostic 1 section, but I agree (and have confirmed), that excluding ERA-Interim will solve the immediate problem here.

**Comment by valeriupredoi** [comment]
in Klaus I trust :us: But here's the thing - Bouwe is right, we should just exclude ERA-I from the mm computation, that'll fix this issue and will buy us time to decide what we do with those plev bounds in the Tool PR
