### ISSUE TITLE
Error when trying to install ESMValCore from source

### ISSUE THREAD

**Issue by thomascrocker** [ESMValGroup/ESMValCore#1358]
I recently created a new conda environment in order to upgrade my local install of ESMValTool.

I followed the steps at https://docs.esmvaltool.org/en/latest/quickstart/installation.html#install-from-source and was able to successfully create the new environment and install ESMValTool. The problem comes when trying to install ESMValCore in editable mode. https://docs.esmvaltool.org/en/latest/quickstart/installation.html#using-the-development-version-of-the-esmvalcore-package

Why does pip say "Build backend does not support editables"? Any ideas how to fix it? I've tried reverting my ESMValCore git to a clone of the main branch, and am working from inside the activated conda environment.

```
[tcrocker@vld372 ESMValCore]$ pip install --editable '.[develop]'
Obtaining file:///net/home/h02/tcrocker/ESMValCore
  Installing build dependencies ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Build backend does not support editables, falling back to setup.py egg_info.
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/users/tcrocker/miniconda3/envs/esmvaltool_dev/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/net/home/h02/tcrocker/ESMValCore/setup.py'"'"'; __file__='"'"'/net/home/h02/tcrocker/ESMValCore/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /var/tmp/pip-pip-egg-info-xalks8av
       cwd: /net/home/h02/tcrocker/ESMValCore/
  Complete output (31 lines):
  /data/users/tcrocker/miniconda3/envs/esmvaltool_dev/bin/python3.8: No module named pip
  Traceback (most recent call last):
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/data/users/tcrocker/miniconda3/envs/esmvaltool_dev/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/data/users/tcrocker/miniconda3/envs/esmvaltool_dev/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/tmpjm6wj8_f', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/net/home/h02/tcrocker/ESMValCore/setup.py", line 188, in <module>
      setup(
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/var/tmp/pip-build-env-2h22kg6a/overlay/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/data/users/tcrocker/miniconda3/envs/esmvaltool_dev/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/tmpjm6wj8_f', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding file:///net/home/h02/tcrocker/ESMValCore. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by remi-kazeroni** [comment]
I also encountered the same problem but for the installation of the ESMValTool. I also followed these [instructions](https://docs.esmvaltool.org/en/latest/quickstart/installation.html#install-from-source). I got the same error message:

```bash
 $ pip install --editable '.[develop]'
Obtaining file:///data/hoss_rm/test/ESMValTool
  Installing build dependencies ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Build backend does not support editables, falling back to setup.py egg_info.
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/hoss_rm/test/conda/envs/test_cf/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/hoss_rm/test/ESMValTool/setup.py'"'"'; __file__='"'"'/data/hoss_rm/test/ESMValTool/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tydm58gx
       cwd: /data/hoss_rm/test/ESMValTool/
  Complete output (31 lines):
  /data/hoss_rm/test/conda/envs/test_cf/bin/python3.9: No module named pip
  Traceback (most recent call last):
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/data/hoss_rm/test/conda/envs/test_cf/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/data/hoss_rm/test/conda/envs/test_cf/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpflwl0xn9', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/data/hoss_rm/test/ESMValTool/setup.py", line 185, in <module>
      setup(
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/tmp/pip-build-env-20r83tlh/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/data/hoss_rm/test/conda/envs/test_cf/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpflwl0xn9', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding file:///data/hoss_rm/test/ESMValTool. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by zklaus** [comment]
As suspected, this is a bug in pip itself: pypa/pip#10573. Will keep you posted on workarounds and how we will proceed.

**Comment by thomascrocker** [comment]
Thanks for the heads up @zklaus I can confirm that from my side, downgrading the version of pip in my conda environment to 21.2.4 appears to have worked. Just off to test some recipes now.

**Comment by valeriupredoi** [comment]
BTW this issue has tripped all the Github Actions in the [nightly tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/1335417439) too so it's definitely not a localized occurrence :grin:

**Comment by valeriupredoi** [comment]
yes or use the workaround in https://github.com/pypa/pip/issues/10573#issuecomment-941136050 but it seems that they already a ready-ish PR that fixes that?
