### ISSUE TITLE
`extract_shape` fails at mask point when run before `area_statistics` since there are cell measure cubes with different shapes than data cube

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1394]
Unmasked (pun intended!) in https://github.com/ESMValGroup/ESMValTool/pull/1832

**Toy recipe**

```yaml
---
documentation:
  title: CMUG diagnostics for sea surface salinity
  description: |
    Recipe for evaluating models against ESACCI Sea Surface Salinity dataset
  authors:
    - vegas-regidor_javier
  maintainer:
    - vegas-regidor_javier
  references:
    - contact_authors
  projects:
    - cmug
preprocessors:
  timeseries:
    extract_shape:
      shapefile: ne_10m_land.shp
      decomposed: True
      method: contains
      crop: False
    area_statistics:
      operator: mean
      fx_variables:
        areacello:
datasets:
  - {project: CMIP6, exp: historical, dataset: MPI-ESM1-2-HR, ensemble: r1i1p1f1,
      start_year: 1950, end_year: 2014, alias: MPI-ESM1-2-HR}
diagnostics:
  compare_salinity:
    description: ESACCI-SEA-SURFACE-SALINITY check
    variables:
      sos:
        preprocessor: timeseries
        mip: Omon
        grid: gn
    scripts: Null
```

**Behavior**

`_area.py/_mask_cube(cube, selections):` tries to `return fix_coordinate_ordering(cubelist.merge_cube())` but the merge operation fails spectacularly with:

```
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 479, in run
    fire.Fire(ESMValTool())
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 423, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 125, in process_recipe
    recipe.run()
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1557, in run
    self.tasks.run(max_parallel_tasks=self._cfg['max_parallel_tasks'])
  File "/home/valeriu/ESMValCore/esmvalcore/_task.py", line 709, in run
    self._run_parallel(max_parallel_tasks)
  File "/home/valeriu/ESMValCore/esmvalcore/_task.py", line 752, in _run_parallel
    _copy_results(task, running[task])
  File "/home/valeriu/ESMValCore/esmvalcore/_task.py", line 775, in _copy_results
    task.output_files, task.products = future.get()
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/valeriu/ESMValCore/esmvalcore/_task.py", line 780, in _run_task
    output_files = task.run()
  File "/home/valeriu/ESMValCore/esmvalcore/_task.py", line 253, in run
    self.output_files = self._run(input_files)
  File "/home/valeriu/ESMValCore/esmvalcore/preprocessor/__init__.py", line 489, in _run
    product.apply(step, self.debug)
  File "/home/valeriu/ESMValCore/esmvalcore/preprocessor/__init__.py", line 356, in apply
    self.cubes = preprocess(self.cubes, step, **self.settings[step])
  File "/home/valeriu/ESMValCore/esmvalcore/preprocessor/__init__.py", line 302, in preprocess
    result.append(_run_preproc_function(function, item, settings))
  File "/home/valeriu/ESMValCore/esmvalcore/preprocessor/__init__.py", line 285, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/valeriu/ESMValCore/esmvalcore/preprocessor/_area.py", line 651, in extract_shape
    return _mask_cube(cube, selections)
  File "/home/valeriu/ESMValCore/esmvalcore/preprocessor/_area.py", line 664, in _mask_cube
    return fix_coordinate_ordering(cubelist.merge_cube())
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/iris/cube.py", line 405, in merge_cube
    (merged_cube,) = proto_cube.merge()
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/iris/_merge.py", line 1325, in merge
    merged_cube = self._get_cube(merged_data)
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/iris/_merge.py", line 1605, in _get_cube
    cube = iris.cube.Cube(
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/iris/cube.py", line 967, in __init__
    self.add_cell_measure(cell_measure, dims)
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/iris/cube.py", line 1197, in add_cell_measure
    data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.9/site-packages/iris/cube.py", line 1130, in _check_multi_dim_metadata
    raise ValueError(
ValueError: Unequal lengths. Cube dimension 1 => 780; metadata 'cell_area' dimension 0 => 404.
```

because, in the case of this recipe, the cube list to merge looks like this:
```
0: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
1: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
2: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
3: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
4: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
5: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
6: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
7: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
8: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
9: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
```

ie one data cube and nine "cell measures" because there are 9 fiona region selections for some reason, ie the region selection happens 9 times but instead of resulting in a single masked cube, it results in individual masked cubes returned, that don't have the same shape as the data cube.

**Logs attached here**

[main_log.txt](https://github.com/ESMValGroup/ESMValCore/files/7547683/main_log.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/7547686/main_log_debug.txt)

**Versions**
esmvalcore/esmvaltool = 2.4.0

**Important note**

By removing the `area_statistics` preprocessor all goes through fine ie the extract region finishes no problemo, followed by:
```
2021-11-16 15:32:33,330 UTC [32647] DEBUG   Running preprocessor step remove_fx_variables
2021-11-16 15:32:33,343 UTC [32647] DEBUG   Running remove_fx_variables(sea_surface_salinity / (0.001)            (time: 780; -- : 10; cell index along second dimension: 404; cell index along first dimension: 802)
```

so I smell a needed removal of fx variables before doing the shape extraction? In the case without `area_statistic`, the cublets in cubeList to be merged have nice dimensions with time:
```
0: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
1: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
2: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
3: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
4: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
5: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
6: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
7: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
8: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
9: sea_surface_salinity / (0.001)      (time: 780; cell index along second dimension: 404; cell index along first dimension: 802)
```

@sloosvel I think you know exactly what the hap is, if not let me know and I'll dig more :smile:

**Comment by sloosvel** [comment]
>so I smell a needed removal of fx variables before doing the shape extraction?

I think that would make `area_statistics` fail. Maybe `_mask_cube` should be expanded to also mask the fx_variables and also make them dependent on the `shape_id` coordinate? I am a bit packed this week to implement this changes though.

**Comment by valeriupredoi** [comment]
Don't be packed, Saskia, it's bad for your back :laughing: I'll have a think on Friday, I am busy writing ISENES3 guff tomorrow :+1:
