### ISSUE TITLE
Specifying wildcards for `timerange` does not work with automatic downloads

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1516]
**Describe the bug**
While conducting tests for #1515 I noticed that specifying wildcards  `timerange` (e.g., `timerange: '*/1950'`) fails when using the automatic download feature.

```bash
Traceback (most recent call last):
  File "/home/manuel/ESMValCore/esmvalcore/_main.py", line 499, in run
    fire.Fire(ESMValTool())
  File "/home/manuel/mambaforge/envs/esm/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/manuel/mambaforge/envs/esm/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/manuel/mambaforge/envs/esm/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/manuel/ESMValCore/esmvalcore/_main.py", line 443, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/manuel/ESMValCore/esmvalcore/_main.py", line 121, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 73, in read_recipe_file
    return Recipe(raw_recipe,
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 1241, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 1850, in initialize_tasks
    tasks = self._create_tasks()
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 1825, in _create_tasks
    new_tasks, failed = self._create_preprocessor_tasks(
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 1785, in _create_preprocessor_tasks
    task = _get_preprocessor_task(
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 1200, in _get_preprocessor_task
    task = _get_single_preprocessor_task(
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 1055, in _get_single_preprocessor_task
    products = _get_preprocessor_products(
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 922, in _get_preprocessor_products
    _update_timerange(variable, config_user)
  File "/home/manuel/ESMValCore/esmvalcore/_recipe.py", line 850, in _update_timerange
    min_date = min(interval[0] for interval in intervals)
ValueError: min() arg is an empty sequence
```

The reason is that in the following lines, `_find_input_files` from the data finder instead of `_get_input_files` is used:

https://github.com/ESMValGroup/ESMValCore/blob/52ecfbda813a6ed11368a2ee723b08bcea310e03/esmvalcore/_recipe.py#L827-L858

**Please attach**

[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/8168865/main_log_debug.txt)

I assign `v2.6.0` here since this has the potential to break a lot of stuff and the current release is almost done.

**Comment by zklaus** [comment]
Would it be easy to add a warning like "Automatic download is not supported with indeterminate time ranges at the moment. Please use a concrete time range in your recipe or run ESMValTool with --offline=True"?

**Comment by schlunma** [comment]
Yes, good idea, will do that while addressing #1515.

**Comment by sloosvel** [comment]
Do you mind if I fix this and #1550 in the same PR? The changes are not that extensive.

**Comment by schlunma** [comment]
Fine for me :+1:
