### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1629]
**Describe the bug**
The docker build is failing with this error:
```
  File "/opt/conda/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mamba/mamba.py", line 914, in main
    from conda.common.compat import ensure_text_type, init_std_stream_encoding

```
While debugging, running the mamba update command works the first time:

```
Looking for: ['conda', 'mamba', 'pip']

conda-forge/noarch                                   8.4MB @   3.5MB/s  2.5s
conda-forge/linux-64                                23.5MB @   3.6MB/s  6.8s

Pinned packages:
  - python 3.9.*


Transaction

  Prefix: /opt/conda

  Updating specs:

   - conda
   - mamba
   - pip
   - ca-certificates
   - certifi
   - openssl


  Package  Version  Build           Channel                  Size
───────────────────────────────────────────────────────────────────
  Upgrade:
───────────────────────────────────────────────────────────────────

  - conda   4.12.0  py39hf3d152e_0  installed                    
  + conda   4.13.0  py39hf3d152e_1  conda-forge/linux-64      1MB

  Summary:

  Upgrade: 1 packages

  Total download: 1MB

───────────────────────────────────────────────────────────────────

conda                                                1.0MB @   3.0MB/s  0.3s
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```
But if you try to run it again, you get the error that appears in the broken build:

```
/src# mamba update -y conda mamba pip
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mamba/mamba.py", line 914, in main
    from conda.common.compat import ensure_text_type, init_std_stream_encoding
```
I suspect it might have something to do with the latest conda version (4.13.0), since the update runs fine the first time but not the second. Should conda just not be updated?

**Comment by sloosvel** [comment]
Opinions are welcome @ESMValGroup/esmvaltool-coreteam , as the release procedure requires all the tests to be passing.

**Comment by bouweandela** [comment]
Related issue: https://github.com/mamba-org/mamba/issues/1706

**Comment by bouweandela** [comment]
Maybe we could just replace this line:
https://github.com/ESMValGroup/ESMValCore/blob/3278472c1ae88276e3116b862f600555982b3bd5/docker/Dockerfile#L7
with
```
RUN    mamba env create --name esmvaltool --file environment.yml \
    && conda clean --all -y
```

**Comment by sloosvel** [comment]
Ok so no update for now, I guess this will have to be updated again when the mamba issue is solved.
