### ISSUE TITLE
Logging in to ESGF crashes the tool when using singularity container

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1631]
Commands to test with singularity:
```bash
docker build -t esmvalcore:latest . -f docker/Dockerfile
singularity build tmp.sif docker-daemon://esmvalcore:latest
singularity run -B $HOME:$HOME tmp.sif run ~/src/esmvalgroup/recipe_standalone.yml
```
where recipe_standalone.yml is a recipe that does not require ESMValTool.

The singularity run ends with
```
2022-06-09 14:13:17,638 UTC [76797] INFO    Loading ESGF configuration from /home/bandela/.esmvaltool/esgf-pyclient.yml
2022-06-09 14:13:17,652 UTC [76797] INFO    Bootstrapping MyProxy server root of trust.
2022-06-09 14:13:17,652 UTC [76797] INFO    Bootstrapping MyProxy server root of trust.
2022-06-09 14:13:19,931 UTC [76797] ERROR   Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/esmvalcore/_main.py", line 499, in run
    fire.Fire(ESMValTool())
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/esmvalcore/_main.py", line 428, in run
    logon()
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/esmvalcore/esgf/_logon.py", line 28, in logon
    manager.logon(**cfg['logon'])
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/pyesgf/logon.py", line 184, in logon
    creds = c.logon(username, password,
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/myproxy/client/__init__.py", line 1453, in logon
    self.getTrustRoots(writeToCACertDir=True,
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/myproxy/client/__init__.py", line 1624, in getTrustRoots
    dat += conn.recv(self.SERVER_RESP_BLK_SIZE)
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1865, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1700, in _raise_ssl_error
    _raise_current_error()
  File "/opt/conda/envs/esmvaltool/lib/python3.10/site-packages/OpenSSL/_util.py", line 55, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'unexpected eof while reading')]
```

if I provide login details in  /home/bandela/.esmvaltool/esgf-pyclient.yml.

_Originally posted by @bouweandela in https://github.com/ESMValGroup/ESMValCore/pull/1630#issuecomment-1151210656_

**Comment by sloosvel** [comment]
Ok, I could reproduce the error and from a quick search it looks like SSL errors when using singularity images is something that happens. But I would need to take a closer look.

**Comment by sloosvel** [comment]
Is this important for this release though? Or could it be left pending?

**Comment by bouweandela** [comment]
It's not important enough to block the release. Maybe I'm somehow not using the container correctly. This means that downloading CORDEX data will not be possible if you use a singularity container, but I suspect that this was already the case before and nobody complained so far.
