### ISSUE TITLE
CMORCheck appears to ignore non-monotonic time coordinate

### ISSUE THREAD

**Issue by evertrol** [ESMValGroup/ESMValCore#173]
Using `CMORCheck` on a file / cube with a non-monotonic time coordinate does not result in an error.
Iris does note the problem, issues a warning, and changes the dimension coordinate to an auxiliary coordinate. Either this auxiliary coordinate is ignored by `CMORCheck().check_metadata()/check_data()`, or it's simply not checked for monotonicity.

Below is a near-minimal example.

----

Python code:

```python
import sys
import iris
from esmvalcore.cmor.check import CMORCheck
from esmvalcore.cmor.table import CMIP5Info

info = CMIP5Info('cmip5-cmor-tables')
varinfo = info.get_variable('Amon', 'tas')
cube = iris.load(sys.argv[1])[0]
print(cube.coord('time').points)
checker = CMORCheck(cube, varinfo,  fail_on_error=False, automatic_fixes=False)
checker.check_data()
checker.check_metadata()
```

Output (ignore the errors about the latitude & longitude unit; see issue #172 ):

```text
/Users/evert/Library/Python/3.7/lib/python/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:2076: UserWarning: Failed to create 'time' dimension coordinate: The points array must be strictly monotonic.
Gracefully creating 'time' auxiliary coordinate instead.
  error=e_msg))
[ 15.5  45.5  74.5 105.  135.5 166.  196.5 227.5 258.  288.5 319.  349.5
  15.5  45.   74.5 105.  135.5 166.  196.5 227.5 258.  288.5 319.  349.5
  15.5  45.   74.5 105.  135.5 166.  196.5 227.5 258.  288.5 319.  349.5]
Traceback (most recent call last):
  File "testcase.py", line 13, in <module>
    checker.check_metadata()
  File "/usr/local/lib/python3.7/site-packages/esmvalcore/cmor/check.py", line 104, in check_metadata
    self.report_errors()
  File "/usr/local/lib/python3.7/site-packages/esmvalcore/cmor/check.py", line 122, in report_errors
    raise CMORCheckError(msg)
esmvalcore.cmor.check.CMORCheckError: There were errors in variable tas:
lon: units should be degrees_east, not degrees
 lat: units should be degrees_north, not degrees
in cube:
air_temperature / (K)               (-- : 36; latitude: 2; longitude: 3)
     Dimension coordinates:
          latitude                      -             x             -
          longitude                     -             -             x
     Auxiliary coordinates:
          time                          x             -             -
     Scalar coordinates:
          height: 2.0 m
     Attributes:
          original_name: 2T
     Cell methods:
          mean: time (3 hours)
```

CDL file:
```text
netcdf bad_time_dimension {
dimensions:
	time = UNLIMITED ;
	lat = 2 ;
	lon = 3 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 2005-1-1" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	double time_bnds(time, bnds) ;
	double lat(lat) ;
		lat:bounds = "lat_bnds" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
	double lat_bnds(lat, bnds) ;
	double lon(lon) ;
		lon:bounds = "lon_bnds" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
	double lon_bnds(lon, bnds) ;
	double height ;
		height:units = "m" ;
		height:axis = "Z" ;
		height:positive = "up" ;
		height:long_name = "height" ;
		height:standard_name = "height" ;
	float tas(time, lat, lon) ;
		tas:standard_name = "air_temperature" ;
		tas:long_name = "Near-Surface Air Temperature" ;
		tas:units = "K" ;
		tas:original_name = "2T" ;
		tas:cell_methods = "time: mean (interval: 3 hours)" ;
		tas:coordinates = "height" ;
		tas:missing_value = 1.e+20f ;
		tas:_FillValue = 1.e+20f ;

data:
  lat = -15, 15 ;
  lat_bnds = -45, 0, 0, 45 ;
  lon = 30, 60, 90;
  lon_bnds = 15, 45, 45, 75, 75, 105 ;
  time = 15.5, 45.5, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5,
    15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5,
	15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5 ;
  time_bnds = 0, 31, 31, 60, 60, 91, 91, 121, 121, 152, 152, 182, 182, 213,
    213, 244, 244, 274, 274, 305, 305, 335, 335, 365,
	0, 31, 31, 60, 60, 91, 91, 121, 121, 152, 152, 182, 182, 213,
    213, 244, 244, 274, 274, 305, 305, 335, 335, 365,
	0, 31, 31, 60, 60, 91, 91, 121, 121, 152, 152, 182, 182, 213,
    213, 244, 244, 274, 274, 305, 305, 335, 335, 365 ;
  height = 2 ;
  tas = 240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240 ;
}
```

**Comment by jvegasbsc** [comment]
Thanks for reporting this. I will take a look

**Comment by mattiarighi** [comment]
Can you check whether #175 solves your issue?
