### ISSUE TITLE
flake8 tests fail locally in current environment

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#189]
When I run test locally (on DKRZ) with

```python -m pytest tests/test_I_like_to_test.py```,

the following error occurs:

```
ERROR    flake8.plugins.manager:manager.py:160 module 'pycodestyle' has no attribute 'maximum_doc_length'
Traceback (most recent call last):
  File "work/miniconda3/envs/esmvaltool/lib/python3.7/site-packages/flake8/plugins/manager.py", line 158, in load_plugin
    self._load()
  File "work/miniconda3/envs/esmvaltool/lib/python3.7/site-packages/flake8/plugins/manager.py", line 135, in _load
    self._plugin = self.entry_point.load()
  File "work/miniconda3/envs/esmvaltool/lib/python3.7/site-packages/entrypoints.py", line 86, in load
    obj = getattr(obj, attr)
AttributeError: module 'pycodestyle' has no attribute 'maximum_doc_length'
CRITICAL flake8.plugins.manager:manager.py:164 Flake8 failed to load plugin "pycodestyle.maximum_doc_length" due to module 'pycodestyle' has no attribute 'maximum_doc_length'.
```

When I install the core in development mode, the following errors occur:

```
ERROR: flake8 3.7.8 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.4.0 which is incompatible.
ERROR: flake8 3.7.8 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 1.6.0 which is incompatible.
```

Can anyone else reproduce these errors? CircleCI seems to run fine. Note that I execute the following commands to install the whole tool, the error above occurs in the very last step:

```
conda env create --name esmvaltool --file ~/ESMValCore/environment.yml
conda env update --name esmvaltool --file ~/ESMValTool/environment.yml
source activate esmvaltool
cd ~/ESMValTool
pip install -e ".[develop]"
cd ~/ESMValCore
pip install -e ".[develop]"
```

**Comment by jvegasbsc** [comment]
Prospector and Flake8 are incompatible,as they require different versions. Prospector is only installed in develop mode, so CircleCI is not affected

**Comment by jvegasbsc** [comment]
Ah, it works when using `python setup.py test` because is temporarily the versions required for flake8

**Comment by valeriupredoi** [comment]
`prospector` is the show stopper:
```
(esmvalcore) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ pip install pycodestyle==2.5.0
Collecting pycodestyle==2.5.0
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
ERROR: prospector 1.1.7 has requirement pycodestyle<=2.4.0,>=2.0.0, but you'll have pycodestyle 2.5.0 which is incompatible.
ERROR: flake8 3.7.8 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 1.6.0 which is incompatible.
Installing collected packages: pycodestyle
  Found existing installation: pycodestyle 2.4.0
    Uninstalling pycodestyle-2.4.0:
      Successfully uninstalled pycodestyle-2.4.0
Successfully installed pycodestyle-2.5.0
(esmvalcore) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ pip install pyflakes==2.1.1
Collecting pyflakes==2.1.1
  Downloading https://files.pythonhosted.org/packages/84/f2/ed0ffb887f8138a8fe5a621b8c0bb9598bfb3989e029f6c6a85ee66628ee/pyflakes-2.1.1-py2.py3-none-any.whl (59kB)
     |████████████████████████████████| 61kB 3.4MB/s 
ERROR: prospector 1.1.7 has requirement pycodestyle<=2.4.0,>=2.0.0, but you'll have pycodestyle 2.5.0 which is incompatible.
ERROR: prospector 1.1.7 has requirement pyflakes<2.0.0,>=0.8.1, but you'll have pyflakes 2.1.1 which is incompatible.
Installing collected packages: pyflakes
  Found existing installation: pyflakes 1.6.0
    Uninstalling pyflakes-1.6.0:
      Successfully uninstalled pyflakes-1.6.0
Successfully installed pyflakes-2.1.1
```
not much we can do, unless we want to lose ` prospector` :grin:

**Comment by bouweandela** [comment]
See e.g. https://github.com/PyCQA/prospector/issues/332.

**Comment by valeriupredoi** [comment]
same story as with cdo=1.9.7.1 that I fought for to be 1. mpi-agnostic (which is now) and 2. not dependent on proj4>=6.1.1 (which is not yet) BAH!

**Comment by Peter9192** [comment]
I had some pytest problems as well. Not the same, but when I tried to reinstall the (develop) environment with latest conda and pip, I noticed: 

```sh
ERROR: After October 2020 you may experience errors when installing or updating packages. 
This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages 
with the new resolver before it becomes the default.
```

Using this option seems to have resolved my conflicts.

**Comment by valeriupredoi** [comment]
see https://github.com/ESMValGroup/ESMValCore/issues/763

**Comment by valeriupredoi** [comment]
this is resolved, pls reopen if issue still present :+1: :beer:
