### ISSUE TITLE
Reading CMIP3 datasets with no dates in the filenames

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1929]
**Describe the bug**
Since #1877, it seems that the Tool no longer supports the usage of CMIP3 datasets that do not contain time information in the filenames. Recipes using CMIP3 datasets can't be run with a recent development installation of the Core (see e.g. this comment https://github.com/ESMValGroup/ESMValTool/pull/2156#pullrequestreview-1296993234). Most CMIP3 data files are named as:
`/work/bd0854/DATA/ESMValTool1/CMIP3/20c3m/atm/mo/tas/bccr_bcm2_0/run1/tas_A1_1.nc` which leads to an error like:

```bash
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 943, in _get_preprocessor_products
    ancestors = _get_ancestors(variable, config_user)
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 600, in _get_ancestors
    (input_files, globs) = _get_input_files(variable, config_user)
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 574, in _get_input_files
    check.data_availability(
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/check.py", line 157, in data_availability
    start, end = _get_start_end_year(file.name)
  File "/home/b/b309192/ESMValCore/esmvalcore/local.py", line 209, in _get_start_end_year
    raise ValueError(f'File {filename} dates do not match a recognized '
ValueError: File tas_A1.nc dates do not match a recognized pattern and time can not be read from the file
```
More examples available on Levante at: `/work/bd0854/DATA/ESMValTool2/CMIP3/20c3m/atm/mo/tas/*/*`

I'm not sure I fully understand what is wrong here because #1877 only changed the error message of `_get_start_end_year` in [local.py](https://github.com/ESMValGroup/ESMValCore/blame/96c270166a4973e3fd64492457f3fc1ea199491f/esmvalcore/local.py)

@bouweandela, would you know what is going on here and how that could be fixed? It would be great to have this in the release so that we can test recipes using CMIP3 data 👍  

**Please attach**
  - A short test version of `bock20jgr/recipe_bock20jgr_fig_1-4.yml`: 
[recipe_bock20jgr_fig_1-4_test.txt](https://github.com/ESMValGroup/ESMValCore/files/10734288/recipe_bock20jgr_fig_1-4_test.txt)

  - The corresponding `main_log_debug.txt` file: 
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/10734290/main_log_debug.txt)

**Comment by remi-kazeroni** [comment]
The problem seems to be solved with:
```diff
--- a/esmvalcore/_recipe/check.py
+++ b/esmvalcore/_recipe/check.py
@@ -153,8 +153,8 @@ def data_availability(input_files, var, patterns, log=True):
     required_years = set(range(start_year, end_year + 1, 1))
     available_years = set()

-    for file in input_files:
-        start, end = _get_start_end_year(file.name)
+    for filename in input_files:
+        start, end = _get_start_end_year(filename)
         available_years.update(range(start, end + 1))
```

**Comment by bouweandela** [comment]
Does that also fix the issue if `input_files` contains `esmvalcore.esgf.ESGFFile`s in addition to `esmvalcore.local.LocalFile`s?

**Comment by remi-kazeroni** [comment]
I didn't think of the possibility of downloading CMIP3 data from ESGF... It seems this is not possible at the moment due to the way CMIP3 datasets are specified in recipes, which is only compatible with the local data pool available at DKRZ. For example:
https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/bock20jgr/recipe_bock20jgr_fig_1-4.yml#L242-L249 
DKRZ facets: `exp: 20c3m`, `frequency: mo`.
ESGF facets: `exp: historical`, `frequency: mon`.

After updating the facets in the recipe above, the tool can successfully search for data on ESGF but the data are not downloaded and the recipe still does not run because of the missing time range in the filenames. This is the case both with the current `main` branch and the fix proposed in this https://github.com/ESMValGroup/ESMValCore/issues/1929#issuecomment-1430022121 

For example, here is the error message when trying to get CMIP3 data with ESGF using `main`:

<details>

```bash
2023-02-15 09:12:08,936 UTC [2087317] DEBUG   Found the following files matching facets {'project': 'CMIP3', 'model': 'bccr_bcm2_0', 'ensemble': 'run1', 'experiment': 'historical', 'time_frequency': 'mon', 'variable': 'tas'}:
ESGFFile:cmip3/BCCR/bccr_bcm2_0/historical/mon/atmos/run1/tas/v1/tas_A1_1.nc on hosts ['aims3.llnl.gov']
ESGFFile:cmip3/BCCR/bccr_bcm2_0/historical/mon/atmos/run1/tas/v1/tas_A1_2.nc on hosts ['aims3.llnl.gov']
2023-02-15 09:12:08,938 UTC [2087317] DEBUG   Selected files:
ESGFFile:cmip3/BCCR/bccr_bcm2_0/historical/mon/atmos/run1/tas/v1/tas_A1_1.nc on hosts ['aims3.llnl.gov']
ESGFFile:cmip3/BCCR/bccr_bcm2_0/historical/mon/atmos/run1/tas/v1/tas_A1_2.nc on hosts ['aims3.llnl.gov']
2023-02-15 09:12:08,938 UTC [2087317] DEBUG   Using input files for variable tas of dataset bccr bcm2 0:
/work/bd0854/DATA/ESMValTool2/download/cmip3/BCCR/bccr_bcm2_0/historical/mon/atmos/run1/tas/v1/tas_A1_1.nc (will be downloaded)
/work/bd0854/DATA/ESMValTool2/download/cmip3/BCCR/bccr_bcm2_0/historical/mon/atmos/run1/tas/v1/tas_A1_2.nc (will be downloaded)
2023-02-15 09:12:09,856 UTC [2087317] INFO    Maximum memory used (estimate): 0.2 GB
2023-02-15 09:12:09,857 UTC [2087317] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2023-02-15 09:12:09,860 UTC [2087317] ERROR   Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/home/b/b309192/ESMValCore/esmvalcore/_main.py", line 490, in run
    fire.Fire(ESMValTool())
  File "/work/bd0854/b309192/soft/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/work/bd0854/b309192/soft/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/work/bd0854/b309192/soft/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/b/b309192/ESMValCore/esmvalcore/_main.py", line 397, in run
    self._run(recipe, session)
  File "/home/b/b309192/ESMValCore/esmvalcore/_main.py", line 437, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/home/b/b309192/ESMValCore/esmvalcore/_main.py", line 124, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 73, in read_recipe_file
    return Recipe(raw_recipe,
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 1262, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 1871, in initialize_tasks
    tasks = self._create_tasks()
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 1846, in _create_tasks
    new_tasks, failed = self._create_preprocessor_tasks(
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 1806, in _create_preprocessor_tasks
    task = _get_preprocessor_task(
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 1221, in _get_preprocessor_task
    task = _get_single_preprocessor_task(
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 1052, in _get_single_preprocessor_task
    products = _get_preprocessor_products(
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 943, in _get_preprocessor_products
    ancestors = _get_ancestors(variable, config_user)
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/recipe.py", line 610, in _get_ancestors
    check.data_availability(input_files, variable, globs)
  File "/home/b/b309192/ESMValCore/esmvalcore/_recipe/check.py", line 157, in data_availability
    start, end = _get_start_end_year(file.name)
  File "/home/b/b309192/ESMValCore/esmvalcore/local.py", line 209, in _get_start_end_year
    raise ValueError(f'File {filename} dates do not match a recognized '
ValueError: File tas_A1_1.nc dates do not match a recognized pattern and time can not be read from the file
2023-02-15 09:12:09,871 UTC [2087317] INFO
```
</details>

In practice, I'm not sure recipes using CMIP3 data (e.g. IPCC recipes with large computational costs) were run on other machines than DKRZ in the past. We could think of updating our recipes to reflect the ESGF facets and to broaden their usage beyond DKRZ. And also reorganize the CMIP3 data pool at DKRZ so that these recipes would still work there. But we would still need a fix for CMIP3 data that do not have years in the filenames. 

For the sake of this release, I would suggest to focus on fixing the Core so that such recipes could be tested as DKRZ as they were before. Making CMIP3 recipes ESGF-compatible is more something for the next release imo. We still have to update our recipes to reflect other changes in the Core before the release (obs4mips entries, ancillary variables, ...) and I'm not in favour of adding another degree of complexity with CMIP3 data which has lower priority imo.

@bouweandela, would you have an idea if there would be possible side-effects to the fix in this https://github.com/ESMValGroup/ESMValCore/issues/1929#issuecomment-1430022121?

**Comment by bouweandela** [comment]
> would you have an idea if there would be possible side-effects to the fix in this https://github.com/ESMValGroup/ESMValCore/issues/1929#issuecomment-1430022121?

Yes, that code is not specific to CMIP3, it runs for any project, so the problem with passing it ESGFFile's is not something that can simply be ignored. An additional check is needed that we only try to open files if they are on the local filesystem. I implemented something in #1936.

> It seems this is not possible at the moment due to the way CMIP3 datasets are specified in recipes

Interesting discovery :eyes: It would be good to open a new issue about that.

**Comment by remi-kazeroni** [comment]
> Interesting discovery 👀 It would be good to open a new issue about that.

Done in https://github.com/ESMValGroup/ESMValTool/issues/3046
