### ISSUE TITLE
Automatic alias definition breaks concatenation of different experiments

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#199]
The new alias definition option (#167) does not work when experiment concatenation is used, e.g. in [examples/recipe_concatenate_exps.yml](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/examples/recipe_concatenate_exps.yml):

```

Traceback (most recent call last):
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_main.py", line 228, in run
    conf = main(args)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_main.py", line 156, in main
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_main.py", line 202, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 70, in read_recipe_file
    raw_recipe, config_user, initialize_tasks, recipe_file=filename)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 806, in __init__
    raw_recipe['diagnostics'], raw_recipe.get('datasets', []))
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 848, in _initialize_diagnostics
    raw_diagnostic.get('additional_datasets', []))
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 946, in _initialize_preprocessor_output
    self._set_alias(preprocessor_output)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 999, in _set_alias
    datasets_info.add(alias)
TypeError: unhashable type: 'list'
2019-08-06 08:18:38,325 UTC [27804] INFO    If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issu
es and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.
```

**Comment by jvegasbsc** [comment]
Will take a look
