### ISSUE TITLE
Dataset problem: Add height coord to ALADIN63 and WRF381P CORDEX datasets

### ISSUE THREAD

**Issue by ljoakim** [ESMValGroup/ESMValCore#2058]
**Describe the dataset issue**
The following two datasets requires additional fixes for height coord, I think they can be dealt with together, so I'm adding them in same issue:

1. [`cnrm_cerfacs_cnrm_cm5.cnrm_aladin63.py`](https://github.com/ESMValGroup/ESMValCore/blob/64f7c0f52f6182cd95a893f6c5522d5d841d270c/esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/cnrm_aladin63.py) has fixes for `Tas` that adds/corrects scalar height coord, which should also be applied to `Tasmin` and `Tasmax`, example dataset:
```
- {dataset: ALADIN63, project: CORDEX, domain: EUR-11,
     exp: [historical, rcp26], ensemble: r1i1p1,
     mip: day, institute: CNRM, rcm_version: v2,
     driver: CNRM-CERFACS-CNRM-CM5, version: [v20190510, v20190702]}
```

2. The `WRF381P` rcm (institute `IPSL`) needs similarly a fix to add height coord, for several drivers, `ICHEC-EC-EARTH`, `CNRM-CERFACS-CNRM-CM5`, `IPSL-IPSL-CM5A-MR`, `MOHC-HadGEM2-ES`, `NCC-NorESM1-M`. The fix should be applied for `Tas`, `Tasmin`, `Tasmax`. Example dataset:
```
- {dataset: WRF381P, project: CORDEX, domain: EUR-11,
     exp: [historical, rcp85], ensemble: r12i1p1,
     mip: day, institute: IPSL, rcm_version: v1,
     driver: ICHEC-EC-EARTH, version: v20200716}
```

Please attach
- The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
Relevant output:
```
Traceback (most recent call last):
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_main.py", line 521, in run
    fire.Fire(ESMValTool())
  File "/home/sm_joalo/.conda/envs/esmvaltool-devel/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/sm_joalo/.conda/envs/esmvaltool-devel/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/sm_joalo/.conda/envs/esmvaltool-devel/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_main.py", line 408, in run
    self._run(recipe, session)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_main.py", line 450, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_main.py", line 122, in process_recipe
    recipe.run()
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_recipe/recipe.py", line 1308, in run
    self.tasks.run(max_parallel_tasks=self.session['max_parallel_tasks'])
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_task.py", line 724, in run
    self._run_parallel(max_parallel_tasks)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_task.py", line 767, in _run_parallel
    _copy_results(task, running[task])
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_task.py", line 790, in _copy_results
    task.output_files, task.products = future.get()
  File "/home/sm_joalo/.conda/envs/esmvaltool-devel/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/sm_joalo/.conda/envs/esmvaltool-devel/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_task.py", line 795, in _run_task
    output_files = task.run()
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/_task.py", line 262, in run
    self.output_files = self._run(input_files)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/preprocessor/__init__.py", line 678, in _run
    product.cubes  # pylint: disable=pointless-statement
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/preprocessor/__init__.py", line 481, in cubes
    self._cubes = [
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/preprocessor/__init__.py", line 482, in <listcomp>
    ds._load_with_callback(callback) for ds in self.datasets
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/dataset.py", line 688, in _load_with_callback
    cube = self._load(callback)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/dataset.py", line 765, in _load
    result = preprocess(
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/preprocessor/__init__.py", line 375, in preprocess
    result.append(_run_preproc_function(function, items, settings,
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/preprocessor/__init__.py", line 328, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/cmor/fix.py", line 159, in fix_metadata
    cube = checker(cube).check_metadata()
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/cmor/check.py", line 188, in check_metadata
    self.report_errors()
  File "/home/sm_joalo/dev/repos/ESMValCore/esmvalcore/cmor/check.py", line 244, in report_errors
    raise CMORCheckError(msg)
esmvalcore.cmor.check.CMORCheckError: There were errors in variable tasmin:
 height2m: does not exist
```

Cheers :beer:

**Comment by mwjury** [comment]
#2333
