### ISSUE TITLE
Input data versions can confuse ESMValTool

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#2239]
Sometimes input data is available in more than one version. This is true both for (CMIP5/6) model data, where a newer version may supersede an older one without the older one being removed from storage, and observational data, where it is common to have several versions of datasets that are retained indefinitely to allow for comparison.

In these cases, at least sometimes, ESMValTool finds several versions and attempts to merge them into one, which fails because they cover the same or overlapping time periods.

Examples of this with snippets from the respective logs include
## recipe_collins13ipcc.yml

```
2023-10-20 07:54:08,008 UTC [149428] ERROR   Failed to run preprocessor function 'cmor_check_metadata' on the data
[<iris 'Cube' of air_temperature / (K) (time: 1151; latitude: 192; longitude: 288)>]
loaded from original input file(s)
[LocalFile('/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ/NCAR/CCSM4/rcp45/mon/atmos/Amon/r1i1p1/v20160829/tas/tas_Amon_CCSM4_rcp45_r1i1p1_200501-210012.nc'),
 LocalFile('/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ/NCAR/CCSM4/rcp45/mon/atmos/Amon/r1i1p1/v20130426/tas/tas_Amon_CCSM4_rcp45_r1i1p1_200601-210012.nc')]
with function argument(s)
check_level = <CheckLevels.DEFAULT: 3>,
cmor_table = 'CMIP5',
mip = 'Amon',
frequency = 'mon',
short_name = 'tas'
2023-10-20 07:54:09,037 UTC [149428] INFO    Maximum memory used (estimate): 0.5 GB
2023-10-20 07:54:09,039 UTC [149428] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2023-10-20 07:54:09,040 UTC [149428] ERROR   Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 518, in run
    fire.Fire(ESMValTool())
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 405, in run
    self._run(recipe, session)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 447, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 130, in process_recipe
    recipe.run()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_recipe/recipe.py", line 1075, in run
    self.tasks.run(max_parallel_tasks=self.session['max_parallel_tasks'])
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 736, in run
    self._run_sequential()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 747, in _run_sequential
    task.run()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 260, in run
    input_files.extend(task.run())
                       ^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 264, in run
    self.output_files = self._run(input_files)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 669, in _run
    product.cubes  # pylint: disable=pointless-statement
    ^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 479, in cubes
    self._cubes = [ds.load() for ds in self.datasets]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 479, in <listcomp>
    self._cubes = [ds.load() for ds in self.datasets]
                   ^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/dataset.py", line 685, in load
    cube = self._load()
           ^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/dataset.py", line 771, in _load
    result = preprocess(
             ^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 378, in preprocess
    result.append(_run_preproc_function(function, item, settings,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 323, in _run_preproc_function
    return function(items, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/cmor/check.py", line 911, in cmor_check_metadata
    cube = checker(cube).check_metadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/cmor/check.py", line 185, in check_metadata
    self.report_errors()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/cmor/check.py", line 247, in report_errors
    raise CMORCheckError(msg)
esmvalcore.cmor.check.CMORCheckError: There were errors in variable tas:
 time: Frequency mon does not match input data
in cube:
air_temperature / (K)               (time: 1151; latitude: 192; longitude: 288)
    Dimension coordinates:
        time                             x               -               -
        latitude                         -               x               -
        longitude                        -               -               x
    Scalar coordinates:
        height                      2.0 m
    Cell methods:
        0                           time: mean (interval: 30 days)
    Attributes:
        Conventions                 'CF-1.4'
        acknowledgements            'The CESM project is supported by the National Science Foundation and the ...'
        associated_files            'baseURL: http://cmip-pcmdi.llnl.gov/CMIP5/dataLocation gridspecFile: gridspec_atmos_fx_CCSM4_rcp45_r0i0p0.nc ...'
        branch_time                 2005.0
        cesm_casename               'b40.rcp4_5.1deg.001'
        cesm_compset                'BRCP45CN'
        cesm_repotag                'ccsm4_0_beta49'
        cmor_version                '2.7.1'
        contact                     'cesm_data@ucar.edu'
        experiment                  'RCP4.5'
        experiment_id               'rcp45'
        forcing                     'Sl GHG Vl SS Ds SA BC MD OC Oz AA'
        forcing_note                'Additional information on the external forcings used in this experiment ...'
        frequency                   'mon'
        initialization_method       1
        institute_id                'NCAR'
        institution                 'NCAR (National Center for Atmospheric Research) Boulder, CO, USA'
        model_id                    'CCSM4'
        modeling_realm              'atmos'
        original_name               'TREFHT'
        parent_experiment           'historical'
        parent_experiment_id        'historical'
        parent_experiment_rip       'r1i1p1'
        physics_version             1
        processed_by                'strandwg on mirage0 at 20111021'
        processing_code_information 'Last Changed Rev: 428 Last Changed Date: 2011-10-21 10:32:02 -0600 (Fri, ...'
        product                     'output'
        project_id                  'CMIP5'
        realization                 1
        references                  'Gent P. R., et.al. 2011: The Community Climate System Model version 4. ...'
        resolution                  'f09_g16 (0.9x1.25_gx1v6)'
        source                      'CCSM4 CCSM4 (repository tag: ccsm4_0_beta49 compset: BRCP45CN)'
        table_id                    'Table Amon (26 July 2011) 976b7fd1d9e1be31dddd28f5dc79b7a1 Table Amon (27 ...'
        title                       'CCSM4 model output prepared for CMIP5 RCP4.5'
loaded from file 
```

## recipe_bock20jgr_fig_1-4.yml

```
2023-10-20 08:26:39,973 UTC [1097995] ERROR   Failed to run preprocessor function 'concatenate' on the data
[<iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 120; latitude: 72; longitude: 144)>,
 <iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 120; latitude: 72; longitude: 144)>,
 <iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 48; latitude: 72; longitude: 144)>,
 <iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 466; latitude: 72; longitude: 144)>]
loaded from original input file(s)
[LocalFile('/work/bd0854/DATA/ESMValTool2/OBS/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_199001-199912.nc'),
 LocalFile('/work/bd0854/DATA/ESMValTool2/OBS/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_200001-200912.nc'),
 LocalFile('/work/bd0854/DATA/ESMValTool2/OBS/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.2_201001-201312.nc'),
 LocalFile('/work/bd0854/DATA/ESMValTool2/OBS/Tier1/GPCP-SG/pr_GPCP-SG_L3_v2.3_197901-201710.nc')]
with function argument(s)
check_level = <CheckLevels.DEFAULT: 3>
2023-10-20 08:26:41,010 UTC [1097995] INFO    Maximum memory used (estimate): 14.2 GB
2023-10-20 08:26:41,011 UTC [1097995] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2023-10-20 08:26:41,012 UTC [1097995] ERROR   Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 518, in run
    fire.Fire(ESMValTool())
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 405, in run
    self._run(recipe, session)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 447, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 130, in process_recipe
    recipe.run()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_recipe/recipe.py", line 1075, in run
    self.tasks.run(max_parallel_tasks=self.session['max_parallel_tasks'])
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 736, in run
    self._run_sequential()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 747, in _run_sequential
    task.run()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 260, in run
    input_files.extend(task.run())
                       ^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 264, in run
    self.output_files = self._run(input_files)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 661, in _run
    product.apply(step, self.debug)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 469, in apply
    self.cubes = preprocess(self.cubes, step,
                            ^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 479, in cubes
    self._cubes = [ds.load() for ds in self.datasets]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 479, in <listcomp>
    self._cubes = [ds.load() for ds in self.datasets]
                   ^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/dataset.py", line 685, in load
    cube = self._load()
           ^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/dataset.py", line 771, in _load
    result = preprocess(
             ^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 374, in preprocess
    result.append(_run_preproc_function(function, items, settings,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 323, in _run_preproc_function
    return function(items, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/_io.py", line 360, in concatenate
    _get_concatenation_error(result)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/_io.py", line 308, in _get_concatenation_error
    raise ValueError(f'Can not concatenate cubes: {msg}')
ValueError: Can not concatenate cubes: failed to concatenate into a single cube.
  Found cubes with overlap on concatenate axis 0, cannot concatenate overlapping cubes
```

## recipe_anav13jclim.yml
This is a special case because here the problem ultimately stems from a bad data situation on the test machine, where two files *with the same version* exist in parallel in the CMIP5 archive. The only difference between the two files is that one covers fewer years at the end of the period. I'd be ok to chalk this up to archive problems that we don't have to deal with, but I suspect that restoring the ability to handle doubly available data will also resolve this problem.

```
2023-10-19 11:40:20,941 UTC [66240] ERROR   Failed to run preprocessor function 'cmor_check_metadata' on the data
[<iris 'Cube' of surface_net_downward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_all_land_processes / (kg m-2 s-1) (time: 1871; latitude: 96; longitude: 96)>]
loaded from original input file(s)
[LocalFile('/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ/IPSL/IPSL-CM5B-LR/historical/mon/land/Lmon/r1i1p1/v20120526/nbp/nbp_Lmon_IPSL-CM5B-LR_historical_r1i1p1_185001-200512.nc'),
 LocalFile('/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ/IPSL/IPSL-CM5B-LR/historical/mon/land/Lmon/r1i1p1/v20120526/nbp/nbp_Lmon_IPSL-CM5B-LR_historical_r1i1p1_197901-200512.nc')]
with function argument(s)
check_level = <CheckLevels.DEFAULT: 3>,
cmor_table = 'CMIP5',
mip = 'Lmon',
frequency = 'mon',
short_name = 'nbp'
[...]
2023-10-19 11:40:22,421 UTC [65962] ERROR   Program terminated abnormally, see stack trace below for more information:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 816, in _run_task
    output_files = task.run()
                   ^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 264, in run
    self.output_files = self._run(input_files)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 661, in _run
    product.apply(step, self.debug)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 469, in apply
    self.cubes = preprocess(self.cubes, step,
                            ^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 479, in cubes
    self._cubes = [ds.load() for ds in self.datasets]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 479, in <listcomp>
    self._cubes = [ds.load() for ds in self.datasets]
                   ^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/dataset.py", line 685, in load
    cube = self._load()
           ^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/dataset.py", line 771, in _load
    result = preprocess(
             ^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 378, in preprocess
    result.append(_run_preproc_function(function, item, settings,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/preprocessor/__init__.py", line 323, in _run_preproc_function
    return function(items, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/cmor/check.py", line 911, in cmor_check_metadata
    cube = checker(cube).check_metadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/cmor/check.py", line 185, in check_metadata
    self.report_errors()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/cmor/check.py", line 247, in report_errors
    raise CMORCheckError(msg)
esmvalcore.cmor.check.CMORCheckError: There were errors in variable nbp:
 time: Frequency mon does not match input data
in cube:
surface_net_downward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_all_land_processes / (kg m-2 s-1) (time: 1871; latitude: 96; longitude: 96)
    Dimension coordinates:
        time                                                                                                       x               -              -
        latitude                                                                                                   -               x              -
        longitude                                                                                                  -               -              x
    Cell methods:
        0                                                                                                     time: mean (interval: 30 minutes)
        1                                                                                                     area: mean where land
    Attributes:
        Conventions                                                                                           'CF-1.4'
        associated_files                                                                                      'baseURL: http://cmip-pcmdi.llnl.gov/CMIP5/dataLocation gridspecFile: grid
spec_land_fx_IPSL-CM5B-LR_historical_r0i0p0.nc ...'
        branch_time                                                                                           1850.0
        cmor_version                                                                                          '2.7.1'
        contact                                                                                               'ipsl-cmip5 _at_ ipsl.jussieu.fr Data manager : Sebastien Denvil'
        experiment                                                                                            'historical'
        experiment_id                                                                                         'historical'
        forcing                                                                                               'Nat,Ant,GHG,SA,Oz,LU,SS,Ds,BC,MD,OC,AA'
        frequency                                                                                             'mon'
        initialization_method                                                                                 1
        institute_id                                                                                          'IPSL'
        institution                                                                                           'IPSL (Institut Pierre Simon Laplace, Paris, France)'
        model_id                                                                                              'IPSL-CM5B-LR'
        modeling_realm                                                                                        'land'
        original_name                                                                                         'nbp'
        parent_experiment                                                                                     'pre-industrial control'
        parent_experiment_id                                                                                  'piControl'
        parent_experiment_rip                                                                                 'r1i1p1'
        physics_version                                                                                       1
        product                                                                                               'output'
        project_id                                                                                            'CMIP5'
        realization                                                                                           1
        references                                                                                            'Model documentation and further reference available here : http://icmc ..
.'
        source                                                                                                'IPSL-CM5B-LR (2011) : atmos : LMDZ5 (LMDZ5_NPv3.1, 96x95x39); ocean : ORC
A2 ...'
        table_id                                                                                              'Table Lmon (31 January 2011) a84ae296f75bb85ff61668fac8fcf090'
        title                                                                                                 'IPSL-CM5B-LR model output prepared for CMIP5 historical'
loaded from file 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 518, in run
    fire.Fire(ESMValTool())
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 405, in run
    self._run(recipe, session)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 447, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_main.py", line 130, in process_recipe
    recipe.run()
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_recipe/recipe.py", line 1075, in run
    self.tasks.run(max_parallel_tasks=self.session['max_parallel_tasks'])
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 738, in run
    self._run_parallel(address, max_parallel_tasks)
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 782, in _run_parallel
    _copy_results(task, running[task])
  File "/home/b/b380866/Projects/ESMValTool/ESMValCore/esmvalcore/_task.py", line 805, in _copy_results
    task.output_files, task.products = future.get()
                                       ^^^^^^^^^^^^
  File "/home/b/b380866/miniforge3/envs/evt-20231018-test/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
esmvalcore.cmor.check.CMORCheckError: There were errors in variable nbp:
 time: Frequency mon does not match input data
in cube:
surface_net_downward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_all_land_processes / (kg m-2 s-1) (time: 1871; latitude: 96; longitude: 96)
    Dimension coordinates:
        time                                                                                                       x               -              -
        latitude                                                                                                   -               x              -
        longitude                                                                                                  -               -              x
    Cell methods:
        0                                                                                                     time: mean (interval: 30 minutes)
        1                                                                                                     area: mean where land
    Attributes:
        Conventions                                                                                           'CF-1.4'
        associated_files                                                                                      'baseURL: http://cmip-pcmdi.llnl.gov/CMIP5/dataLocation gridspecFile: grid
spec_land_fx_IPSL-CM5B-LR_historical_r0i0p0.nc ...'
        branch_time                                                                                           1850.0
        cmor_version                                                                                          '2.7.1'
        contact                                                                                               'ipsl-cmip5 _at_ ipsl.jussieu.fr Data manager : Sebastien Denvil'
        experiment                                                                                            'historical'
        experiment_id                                                                                         'historical'
        forcing                                                                                               'Nat,Ant,GHG,SA,Oz,LU,SS,Ds,BC,MD,OC,AA'
        frequency                                                                                             'mon'
        initialization_method                                                                                 1
        institute_id                                                                                          'IPSL'
        institution                                                                                           'IPSL (Institut Pierre Simon Laplace, Paris, France)'
        model_id                                                                                              'IPSL-CM5B-LR'
        modeling_realm                                                                                        'land'
        original_name                                                                                         'nbp'
        parent_experiment                                                                                     'pre-industrial control'
        parent_experiment_id                                                                                  'piControl'
        parent_experiment_rip                                                                                 'r1i1p1'
        physics_version                                                                                       1
        product                                                                                               'output'
        project_id                                                                                            'CMIP5'
        realization                                                                                           1
        references                                                                                            'Model documentation and further reference available here : http://icmc ..
.'
        source                                                                                                'IPSL-CM5B-LR (2011) : atmos : LMDZ5 (LMDZ5_NPv3.1, 96x95x39); ocean : ORC
A2 ...'
        table_id                                                                                              'Table Lmon (31 January 2011) a84ae296f75bb85ff61668fac8fcf090'
        title                                                                                                 'IPSL-CM5B-LR model output prepared for CMIP5 historical'
loaded from file 
```

**Comment by bouweandela** [comment]
The tool has the ability to automatically use just one file if multiple files provide the same data for the same time period. Of course this feature can also hide problems with selecting the wrong input files. This is done by the preprocessor function concatenate, which recently had seen a bit of work on it, maybe something changed there? See #2144.
