### ISSUE TITLE
Supplementary datasets not required to have the same version of the dataset

### ISSUE THREAD

**Issue by k-a-webb** [ESMValGroup/ESMValCore#2523]
This issue is mainly to report the unexpected behaviour related to sourcing supplementary datasets.

I encountered an issue related to the code [esmvalcore._recipe.to_datasets.py L236-237](https://github.com/ESMValGroup/ESMValCore/blob/21ce35a73336075e022d65fd867e1e50d6780bff/esmvalcore/_recipe/to_datasets.py#L237):
```
if 'version' in facets:
    supplementary_facets['version'] = '*'
```

The issue stems from the fact that I have different versions of my datasets with different gridding, and thus not sharing supplementary files. For example,
```
dataset/v1_oceanGrid/
dataset/v1_oceanGrid/fx/areacella/<supplementary file>
dataset/v1_latlonGrid/
```

When attempting to use the dataset version "v1_latlonGrid", because the supplementary datasets are not version-specific (see code above), it grabbed the supplementary files from the incorrect version. This lead to the following error message:

```
2024-09-11 19:36:50,328 UTC [2605922] ERROR   Failed to run preprocessor function 'add_supplementary_variables' on the data
[<iris 'Cube' of sea_ice_area_fraction / (%) (time: 24; latitude: 360; longitude: 720)>]
loaded from original input file(s)
[LocalFile('/space/hall5/sitestore/eccc/crd/ccrn/users/rkw001/data/CMOROBS/reanaly/NSIDC-G02202-sh/4LonLatGrid/mon/siconc/OBS6_NSIDC-G02202-sh_reanaly_4LonLatGrid_SImon_siconc_198101-198112.nc'),
 LocalFile('/space/hall5/sitestore/eccc/crd/ccrn/users/rkw001/data/CMOROBS/reanaly/NSIDC-G02202-sh/4/fx/areacello/OBS6_NSIDC-G02202-sh_reanaly_4_Ofx_areacello.nc')]
with function argument(s)
supplementary_cubes = [<iris 'Cube' of cell_area / (m2) (y: 332; x: 316)>]
2024-09-11 19:36:50,574 UTC [2605718] INFO    Maximum memory used (estimate): 0.0 GB
2024-09-11 19:36:50,575 UTC [2605718] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2024-09-11 19:36:50,575 UTC [2605718] ERROR   Program terminated abnormally, see stack trace below for more information:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkw001/miniconda3/envs/a4d_env_v1.5/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/_task.py", line 816, in _run_task
    output_files = task.run()
                   ^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/_task.py", line 264, in run
    self.output_files = self._run(input_files)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/__init__.py", line 709, in _run
    product.apply(step, self.debug)
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/__init__.py", line 514, in apply
    self.cubes = preprocess(self.cubes, step,
                            ^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/__init__.py", line 527, in cubes
    self._cubes = [ds.load() for ds in self.datasets]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/__init__.py", line 527, in <listcomp>
    self._cubes = [ds.load() for ds in self.datasets]
                   ^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/dataset.py", line 695, in load
    cubes = preprocess(
            ^^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/__init__.py", line 420, in preprocess
    result.append(_run_preproc_function(function, item, settings,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/__init__.py", line 365, in _run_preproc_function
    return function(items, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/_supplementary_vars.py", line 139, in add_supplementary_variables
    add_cell_measure(cube, supplementary_cube, measure_name)
  File "/fs/site5/eccc/crd/ccrn/users/rkw001/code/esmvalcore/ESMValCore_v2.11.0/esmvalcore/preprocessor/_supplementary_vars.py", line 76, in add_cell_measure
    cube.add_cell_measure(measure, range(start_dim, cube.ndim))
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkw001/miniconda3/envs/a4d_env_v1.5/lib/python3.11/site-packages/iris/cube.py", line 1640, in add_cell_measure
    data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/space/hall5/sitestore/eccc/crd/ccrn/users/rkw001/miniconda3/envs/a4d_env_v1.5/lib/python3.11/site-packages/iris/cube.py", line 1523, in _check_multi_dim_metadata
    raise iris.exceptions.CannotAddError(
iris.exceptions.CannotAddError: Unequal lengths. Cube dimension 1 => 360; metadata 'cell_area' dimension 0 => 332.
"""

```

Commenting out lines 236-237 (i.e., forcing the supplementary datasets to have the same version of the data) resolved the error, and the recipe ran successfully.
I could also solve this issue by having separate directories for datasets with different gridding -- i.e., not including the grid label in the "version".

While I can appreciate the convenience of not having to create duplicate supplementary files for multiple versions, this behaviour was not expected. And I think it could cause issues were supplementary files **are** version-specific.

**Comment by bouweandela** [comment]
CMIP6 and CMIP5 supplementary variables often do not have the same version as the main variable, that's why the 'automagic' adding of supplementary variables works like this. If you need a specific version or any other specific facet for the supplementary variable, it can be specified in the recipe as described [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/overview.html#defining-supplementary-variables-ancillary-variables-and-cell-measures) in the documentation. If you think this could be explained more clearly, a pull request would be very welcome.

**Comment by k-a-webb** [comment]
Thank you for pointing out the section in the documentation, I think it clearly explains how supplementary datasets can be explicitly configured. I do think the addition of a note that the supplementary datasets do not inherit the version facet of the data would be worthwhile. (I'll note however this is behaviour is noted in the INFO log). 

That said, for my situation the problem is that my dataset explicitly _does not_ have supplementary datasets. 
Including a `supplementary_variables` parameter with my dataset does not seem to help.
- If I explicitly set the list of supplementary variables to be empty (`supplementary_variables: []`) the code proceeds as if I had not set it at all (i.e., looking for any supplementary datasets under any version).
- If I instead set the supplementary variable version to be the same as the dataset, the code will fail because that dataset does not exist. 

If there is another way to explicitly setup the recipe such that the supplementary datasets are null, I'd be grateful to know.
Otherwise, I would suggest including a note about this caveat in the documentation.

**Comment by bouweandela** [comment]
> If there is another way to explicitly setup the recipe such that the supplementary datasets are null, I'd be grateful to know.

This is possible and explained in the last paragraph of the linked docs:

> To disable this automatic addition, define the supplementary variable as usual, but add the special facet skip with value true. See [Supplementary variables (ancillary variables and cell measures)](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#preprocessors-using-supplementary-variables) for an example recipe.

**Comment by k-a-webb** [comment]
Thank you for your help!
