### ISSUE TITLE
Mamba installation issue 

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValCore#2608]
I am trying to update `mamba` to install a new development version of ESMvalTool and ESMValCore under my home directory on JASMIN. The first step in that process was to update `mamba`. 

When I execute 

` >mamba update --name base mamba conda`

I get the following error message

```
Traceback (most recent call last):
  File "/home/users/ranjinis/miniforge3/condabin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/users/ranjinis/miniforge3/lib/python3.10/site-packages/mamba/mamba.py", line 18, in <module>
    from conda.cli.main import generate_parser, init_loggers
ImportError: cannot import name 'generate_parser' from 'conda.cli.main' (/home/users/ranjinis/miniforge3/lib/python3.10/site-packages/conda/cli/main.py)
```
I see that it is related to the GitHub issue [here](https://github.com/mamba-org/mamba/issues/3520) but I don't know how to follow their suggestion of removing all mamba/conda installations.
The current version of `conda` ia have is 
```
>conda --version
conda 24.9.2
```
@valeriupredoi  - Any suggestions?

**Comment by valeriupredoi** [comment]
best bet is to install with the latest miniconda installer then install `mamba` in `(base)` with `conda install -c conda-forge mamba`; if you'd like to keep the old infrastructure, but just update `conda/mamba` then run `conda update -n base conda mamba` (note the use of `conda` exceutable, not `mamba`) :beer:

**Comment by valeriupredoi** [comment]
doing that gives me:
```
valeriu@valeriu-PORTEGE-Z30-C:~$ mamba -V
mamba 1.5.11
conda 24.11.0
```

be careful with `mamba>=2` - there are some compat issues with it

**Comment by valeriupredoi** [comment]
also, I'd really upgrade from Python 3.10 to 3.11 or 3.12 if I was you :grin:

**Comment by rswamina** [comment]
Thanks..let me try these.

**Comment by bouweandela** [comment]
> I don't know how to follow their suggestion of removing all mamba/conda installations.

Run `rm -r /home/users/ranjinis/miniforge3`

**Comment by valeriupredoi** [comment]
any luck on this @rswamina ? :beer:

**Comment by rswamina** [comment]
I was able to successfully install mamba and conda and update them. I now see : 
```
(base) /home/users/ranjinis>mamba --version
2.0.6
(base) /home/users/ranjinis>conda --version
conda 25.1.1
```
I'd like to proceed with this but am a bit unsure regarding the compatibility issues associated with `mamba > 2.0` as mentioned above. If it is ok to carry on and revisit by creating a new issue in case such compatibility issues arise, then I am happy to close this issue. @valeriupredoi and @bouweandela - thanks for your suggestions, they seem to have worked.

**Comment by valeriupredoi** [comment]
Good work @rswamina - nay bother about mamba >2, should be fine - check the Dask and iris versions after env creation, but you'll get dask=2025 and itis=3.11.0 which is just fine 🍺

**Comment by valeriupredoi** [comment]
Looks A-class @rswamina 👍🍺
