### ISSUE TITLE
Hard to understand error about missing CMOR tables when a directory cmip5 is present in current working directory

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#316]
When there is a directory called `cmip5` in the current working directory, the `esmvaltool` command fails:
```
$ mkdir cmip5
$ esmvaltool -c ~/.esmvaltool/config-user.yml examples/recipe_python.yml
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/home/bandela/src/esmvalcore/esmvalcore/_main.py", line 228, in run
    conf = main(args)
  File "/home/bandela/src/esmvalcore/esmvalcore/_main.py", line 122, in main
    cfg = read_config_user_file(config_file, recipe_name)
  File "/home/bandela/src/esmvalcore/esmvalcore/_config.py", line 93, in read_config_user_file
    read_cmor_tables(CFG)
  File "/home/bandela/src/esmvalcore/esmvalcore/cmor/table.py", line 44, in read_cmor_tables
    table_path, default=custom, strict=cmor_strict,
  File "/home/bandela/src/esmvalcore/esmvalcore/cmor/table.py", line 537, in __init__
    self._cmor_folder)
NotADirectoryError: [Errno 20] CMOR tables path is not a directory: 'cmip5/Tables'
```

**Comment by valeriupredoi** [comment]
Holy Welsh socks, how on Earth did you find this? See #334
