### ISSUE TITLE
Check for parent_time_units fails if set to "no parent"

### ISSUE THREAD

**Issue by hb326** [ESMValGroup/ESMValCore#341]
According to [this](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit) document it is possible to specify `no parent` as valid attribute for `parent_time_units`. However, this entry raises the following error:
```
Traceback (most recent call last):
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_main.py", line 228, in run
    conf = main(args)
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_main.py", line 156, in main
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_main.py", line 206, in process_recipe
    recipe.run()
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_recipe.py", line 1277, in run
    max_parallel_tasks=self._cfg['max_parallel_tasks'])
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_task.py", line 597, in run_tasks
    _run_tasks_sequential(tasks)
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_task.py", line 609, in _run_tasks_sequential
    task.run()
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/_task.py", line 230, in run
    self.output_files = self._run(input_files)
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/preprocessor/__init__.py", line 403, in _run
    product.apply(step, self.debug)
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/preprocessor/__init__.py", line 271, in apply
    self.cubes = preprocess(self.cubes, step, **self.settings[step])
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/preprocessor/__init__.py", line 213, in preprocess
    result.append(_run_preproc_function(function, items, settings))
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/preprocessor/__init__.py", line 199, in _run_preproc_function
    return function(items, **kwargs)
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/cmor/fix.py", line 145, in fix_metadata
    cube = checker(cube).check_metadata()
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/cmor/check.py", line 102, in check_metadata
    self._check_time_coord()
  File "/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/cmor/check.py", line 488, in _check_time_coord
    simplified_cal)
  File "/pf/b/b309143/miniconda3/envs/esmvaltool-private4/lib/python3.7/site-packages/cf_units/__init__.py", line 873, in __init__
    six.raise_from(value_error, None)
  File "<string>", line 3, in raise_from
ValueError: [UT_UNKNOWN] Failed to parse unit "no parent"

```

**Comment by zklaus** [comment]
Hm, strange. This case was specifically addressed in #231, but the line numbers in your complaint check out. Could you please double check that you are on the current development version of the core, perhaps email me the file
`/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/cmor/check.py` ?

**Comment by hb326** [comment]
> 
> 
> Hm, strange. This case was specifically addressed in #231, but the line numbers in your complaint check out. Could you please double check that you are on the current development version of the core, perhaps email me the file
> `/mnt/lustre01/pf/b/b309143/ESMValCore/esmvalcore/cmor/check.py` ?

Will check that I am in the latest development branch now.

**Comment by hb326** [comment]
Ha, looks like I use an old version of the development branch. I had thought I had pulled the latest version...
I will do so now and try again.

**Comment by hb326** [comment]
Works like a charm.
Thanks!
