### ISSUE TITLE
Changing unit dimensionality in depth integration pre-processor

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#60]
Depth integration is a common methods used to evalaute ocean behaviour, notably in the "integrated primary production" marine biogeochemistry metric. Depth integration typically converts concentration in volume into concentration in area. This means that the units go from mol m-3 to mol m-2, and so the units need to be changed. 

This  function already exists in the [volume preprocessor](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/preprocessor/_volume_pp.py), but does not currently change the units. Basically, I want to include this command in the preprocessor:
```
result.units = Unit('m') * result.units
```
but this does not work for me. 

@bouweandela suggested in issue #604: _"This would require a minor modification to the code so the unit is read from the cube instead of from the cmor table of the input data when extracting the metadata, but should be possible. Please make an issue if you would like this functionality."_

So here is the issue. Fingers crossed it is actually easy to resolve!

**Comment by valeriupredoi** [comment]
can now use the `convert_units` preprocessor step :beer:

**Comment by bouweandela** [comment]
Related to #505

**Comment by schlunma** [comment]
I don't think we can close this, `convert_units` (hopefully) doesn't convert units from `mol m-3` to `mol m -2`.

**Comment by valeriupredoi** [comment]
why not? It's a valid CF unit, the cube doesn't care if it's `cows / vultures` as long as they are CF units, it's CMOR that will be barking at you, but you're on your own there

**Comment by schlunma** [comment]
```
>>> from cf_units import Unit
>>> a = Unit('kg m-3')
>>> b = Unit('kg m-2')
>>> a.convert(1, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/lustre02/work/bd0854/b309141/miniconda3/envs/mlr/lib/python3.7/site-packages/cf_units/__init__.py", line 1907, in convert
    (self, other))
ValueError: Unable to convert from 'Unit('kg m-3')' to 'Unit('kg m-2')'.
>>> 
```

**Comment by valeriupredoi** [comment]
`ValueError: Unable to convert from 'Unit('mol m-3')' to 'Unit('mol m-2')'.` :man_facepalming:

**Comment by ledm** [comment]
We shouldn't be using iris `convert` here, that isn't what happenning here. Iris convert is for stuff like Celsius to Kelvin, not Celsius to heat. The convert function should not be able to change the dimensions of the units. 

The issue here is that the `depth_integration` preprocessor changes the units, dimensions and the dataset standard name. It's a very simple calculation, but non-trivial to resolve it, as the output may not necessarily exist in the CMOR tables.

For instance, you may want to know the water column total oxygen, in mmol per meter squared. I bet that field doesn't exists a standard variable.

**Comment by bouweandela** [comment]
@ledm That should no longer be a problem, because we moved the cmor check to right after the data is loaded in #743, so there is no CMOR check anymore after the `depth_integration` function is applied.

**Comment by schlunma** [comment]
This is implemented now (https://github.com/ESMValGroup/ESMValCore/pull/2139).
