### ISSUE TITLE
Improve error messages resulted from recipe checks with yamale schema

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#681]
At the moment I am running a recipe that seems fine to me but all I get is this obscure message:
```bash
2020-06-18 11:11:10,143 UTC [97387] ERROR   esmvalcore._main:247 Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/home/users/valeriu/esmvalcore/esmvalcore/_main.py", line 242, in run
    conf = main(args)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_main.py", line 176, in main
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_main.py", line 224, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_recipe.py", line 70, in read_recipe_file
    raw_recipe = load_raw_recipe(filename)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_recipe.py", line 57, in load_raw_recipe
    check.recipe_with_schema(filename)
  File "/home/users/valeriu/esmvalcore/esmvalcore/_recipe_checks.py", line 50, in recipe_with_schema
    yamale.validate(schema, recipe)
  File "/home/users/valeriu/anaconda3R/envs/esmvaltool/lib/python3.8/site-packages/yamale/yamale.py", line 38, in validate
    schema.validate(d, path, strict)
  File "/home/users/valeriu/anaconda3R/envs/esmvaltool/lib/python3.8/site-packages/yamale/schema/schema.py", line 65, in validate
    raise ValueError(error_str)
ValueError:
Error validating data /home/users/valeriu/esmvaltool_var_test/recipe_lisa.yml with schema /home/users/valeriu/esmvalcore/esmvalcore/recipe_schema.yml
         : 'None' is not a map
2020-06-18 11:11:10,148 UTC [97387] INFO    esmvalcore._main:251 If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.
```
Obviously I am missing a field, but which one? :beer:

**Comment by valeriupredoi** [comment]
in my case the error was coming from actually having two `---` at the start of the recipe:
```yaml
# bsbsbsbs
---
---
```
This should be nicely reported :grin:
