### ISSUE TITLE
cmorize_obs is broken

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#705]
My guess would be that it is related to the recent change to using `fire`. 

```
Traceback (most recent call last):
  File "/net/exo/landclim/crezees/conda/envs/esmvaltool-public/bin/cmorize_obs", line 11, in <module>
    load_entry_point('ESMValTool', 'console_scripts', 'cmorize_obs')()
  File "/home/crezees/ESMValTool/esmvaltool/cmorizers/obs/cmorize_obs.py", line 166, in main
    config_user = read_config_user_file(config_file, 'cmorize_obs')
TypeError: read_config_user_file() missing 1 required positional argument: 'options'
```

**Comment by mattiarighi** [comment]
See https://github.com/ESMValGroup/ESMValCore/pull/709

**Comment by bascrezee** [comment]
Thanks. Good to have a branch where it is working for now.

**Comment by mattiarighi** [comment]
Plan to merge it soon.

**Comment by bascrezee** [comment]
Thanks. So how am I supposed to run it now? I don't get `cmorize_obs` working yet.

**Comment by mattiarighi** [comment]
`--config_file` instead of `-c` should do it.

**Comment by bascrezee** [comment]
Hmmm, not yet. 

```
$   cmorize_obs --config-file config-ETH-LANDCLIM.yml -o CDS-SATELLITE-SOIL-MOISTURE

Traceback (most recent call last):
  File "/conda/envs/esmvaltool-public/bin/cmorize_obs", line 11, in <module>
    load_entry_point('ESMValTool', 'console_scripts', 'cmorize_obs')()
  File "/ESMValTool/esmvaltool/cmorizers/obs/cmorize_obs.py", line 175, in main
    output=run_dir, console_log_level=config_user['log_level'])
TypeError: configure_logging() got an unexpected keyword argument 'output'


```

**Comment by mattiarighi** [comment]
Please report on #709
