### ISSUE TITLE
--diagnostics option in CLI fails

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#712]
**Describe the bug**
While testing another PR (ESMValGroup/ESMValTool#1585) for ESMValTool I noticed that the `--diagnostics` option in the new CLI does not seem to work. I tried

```
esmvaltool run ~/ESMValTool/esmvaltool/recipes/recipe_ecs_constraints.yml --diagnostics diag_x_volodin_cmip5 --config-file ~/config/mymodels.yml
```

and 

```
esmvaltool run ~/ESMValTool/esmvaltool/recipes/recipe_ecs_constraints.yml --config-file ~/config/mymodels.yml --diagnostics diag_x_volodin_cmip5
```

for [this](https://github.com/ESMValGroup/ESMValTool/blob/add_ecs_constraints/esmvaltool/recipes/recipe_ecs_constraints.yml) recipe.

**Output**

```
...
2020-07-14 08:55:48,077 UTC [17726] INFO    Creating diagnostic task diag_x_su_hur_cmip5/ecs_predictor
2020-07-14 08:55:48,077 UTC [17726] INFO    Creating diagnostic task diag_x_su_hur_cmip5/emergent_constraint
2020-07-14 08:55:48,094 UTC [17726] INFO    These tasks will be executed: 
2020-07-14 08:55:48,099 UTC [17726] INFO    Running 0 tasks using 0 processes
2020-07-14 08:55:48,277 UTC [17726] INFO    Maximum memory used (estimate): 0.2 GB
2020-07-14 08:55:48,277 UTC [17726] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2020-07-14 08:55:48,279 UTC [17726] ERROR   Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/ESMValCore/esmvalcore/_main.py", line 428, in run
    fire.Fire(ESMValTool())
  File "/miniconda3/envs/mlr/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/miniconda3/envs/mlr/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/miniconda3/envs/mlr/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/ESMValCore/esmvalcore/_main.py", line 405, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/ESMValCore/esmvalcore/_main.py", line 98, in process_recipe
    recipe.run()
  File "/ESMValCore/esmvalcore/_recipe.py", line 1358, in run
    run_tasks(self.tasks,
  File "/ESMValCore/esmvalcore/_task.py", line 643, in run_tasks
    _run_tasks_parallel(tasks, max_parallel_tasks)
  File "/ESMValCore/esmvalcore/_task.py", line 674, in _run_tasks_parallel
    with Pool(processes=max_parallel_tasks) as pool:
  File "/miniconda3/envs/mlr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/miniconda3/envs/mlr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
2020-07-14 08:55:48,285 UTC [17726] INFO    If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.
```

Please note this line: **`Running 0 tasks using 0 processes`**

Am I doing something wrong here? If not this needs to be fixed before the release of v2.0.0

**Comment by jvegasbsc** [comment]
Should be fixed in #713
