### ISSUE TITLE
Add completion command for automatic command line completion

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#804]
As done for example here: https://cli.github.com/manual/gh_completion

The functionality is already there through fire: https://google.github.io/python-fire/using-cli/#python-fires-flags, but it would be nice to make this more automatic and easier to find, e.g. do this automatically when the conda environment is loaded?

**Comment by bouweandela** [comment]
But we would need to take into consideration that probably the `esmvaltool` command is not available yet when people start their shell, so it will only be available after activating the conda environment.

**Comment by bouweandela** [comment]
Looks like the --completion command is broken anyway:
```
$ esmvaltool -- --completion
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_main.py", line 635, in run
    fire.Fire(ESMValTool())
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/core.py", line 600, in _Fire
    script = CompletionScript(name, initial_component, shell=show_completion)
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/core.py", line 174, in CompletionScript
    return completion.Script(name, component, shell=shell)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 31, in Script
    return _BashScript(name, _Commands(component), default_options)
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 49, in _BashScript
    global_options, options_map, subcommands_map = _GetMaps(
                                                   ~~~~~~~~^
        name, commands, default_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 499, in _GetMaps
    for command in commands:
                   ^^^^^^^^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 471, in _Commands
    for command in _Commands(member, depth - 1):
                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 471, in _Commands
    for command in _Commands(member, depth - 1):
                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 464, in _Commands
    for member_name, member in VisibleMembers(component, class_attrs={},
                               ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              verbose=False):
                                              ^^^^^^^^^^^^^^
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/site-packages/fire/completion.py", line 362, in VisibleMembers
    members = inspect.getmembers(component)
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/inspect.py", line 624, in getmembers
    return _getmembers(object, predicate, getattr)
  File "/home/bandela/mambaforge/envs/esmvaltool/lib/python3.13/inspect.py", line 602, in _getmembers
    value = getter(object, key)
  File "/home/bandela/src/esmvalgroup/esmvaltool/esmvaltool/cmorizers/data/cmorizer.py", line 128, in log_level
    return self.config["log_level"]
           ~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

It would be nice if someone would have time to fix this (and perhaps [integrate it into the conda package](https://conda.discourse.group/t/how-to-install-a-bash-completion-script-for-my-conda-forge-package/304)) as this issue suggested.
