### ISSUE TITLE
The target grid for regridding in recipe SMPI is sometimes not read correctly

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#817]
@bascrezee said: I thought I also quickly test `recipe_smpi.yml` from the master branch. I am testing with `master` branch of ESMValTool and `release_2.1` from ESMValCore (just checkin). This is the error message I get, hope it helps. 
```
 in memory consumption occur.
2020-10-07 14:13:26,492 UTC [36998] ERROR   Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/home/crezees/ESMValCore/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/net/exo/landclim/crezees/conda/envs/esmvaltool-pub/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/net/exo/landclim/crezees/conda/envs/esmvaltool-pub/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/net/exo/landclim/crezees/conda/envs/esmvaltool-pub/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/crezees/ESMValCore/esmvalcore/_main.py", line 407, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/crezees/ESMValCore/esmvalcore/_main.py", line 94, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 71, in read_recipe_file
    return Recipe(raw_recipe,
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 951, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 1299, in initialize_tasks
    task = _get_preprocessor_task(
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 917, in _get_preprocessor_task
    task = _get_single_preprocessor_task(
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 776, in _get_single_preprocessor_task
    products = _get_preprocessor_products(
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 733, in _get_preprocessor_products
    _update_target_grid(
  File "/home/crezees/ESMValCore/esmvalcore/_recipe.py", line 198, in _update_target_grid
    parse_cell_spec(settings['regrid']['target_grid'])
  File "/home/crezees/ESMValCore/esmvalcore/preprocessor/_regrid.py", line 87, in parse_cell_spec
    raise ValueError(emsg.format(spec))
ValueError: Invalid MxN cell specification for grid, got 'reference_dataset'.
```

_Originally posted by @bascrezee in https://github.com/ESMValGroup/ESMValCore/issues/812#issuecomment-704967559_

**Comment by bouweandela** [comment]
@hb326 reported a different problem, in her case all variables in the recipe are regridded to the grid of model GFDL-ESM2G, while the recipe specifies either the `reference_dataset` (ERA-Interim in most cases) and a `1x1` grid for datasets on an irregular grid as the target grid, see [main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/5340989/main_log_debug.txt).

**Comment by bouweandela** [comment]
@hb326 @bascrezee Could you please post the result of `conda env export`, so I can try to reproduce the problem with the same software versions as you have? For me and @valeriupredoi it works as expected, so maybe it's related to some software version you're using?

Here is my conda environment: [environment.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/5346251/environment.yml.txt) (the .txt is only there because GitHub doesn't allow uploading .yml files). To create an environment from this file, you would use `conda env create -n test -f environment.yml.txt`. Both ESMValTool and ESMValCore need to be installed from source after creating the environment using `pip install .`.

**Comment by bouweandela** [comment]
Note that you can see which `target_grid` the ESMValCore is planning to use for regridding by looking for `target_grid` in the main_log_debug.txt file.

**Comment by valeriupredoi** [comment]
cheers much @bouweandela - I will rerun this (again) fully (I have run only for the Japanese model previously because Jasmin node memory is scant, but I found me a new Jasmin node with plenty of mem) and will post the env here too :beer:

**Comment by hb326** [comment]
> 
> 
> Note that you can see which `target_grid` the ESMValCore is planning to use for regridding by looking for `target_grid` in the main_log_debug.txt file.

@bouweandela: this it the environment I am using: 
[environment_BH.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/5354693/environment_BH.yml.txt)

**Comment by bouweandela** [comment]
Please reopen if still relevant.
