### ISSUE TITLE
OSError: [Errno 8] Exec format error: '.../custom_recipe.py'

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValCore#828]
**Describe the bug**
If I'm working on my local recipes (outside the tool), I sometimes come accross this error.

The recommended solution: `chmod -x /home/stef/s/warming_stripes.py`, does not work. 

I have narrowed it down to the fact that subprocess calls the script directly (without the python executable). So, as a work-around, the shell environment can be added to the top of the file, i.e. `#!/usr/bin/env python`.

<details>
<pre>
2020-10-13 13:09:15,885 UTC [13389] ERROR   Diagnostic script has its executable bit set, but is not executable. To fix this run:
chmod -x /home/stef/s/warming_stripes.py
2020-10-13 13:09:15,886 UTC [13389] ERROR   You may also need to fix this in the git repository.
2020-10-13 13:09:15,946 UTC [13381] INFO    Progress: 1 tasks running, 0 tasks waiting for ancestors, 1/2 done
2020-10-13 13:09:16,485 UTC [13381] INFO    Maximum memory used (estimate): 0.6 GB
2020-10-13 13:09:16,488 UTC [13381] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2020-10-13 13:09:16,506 UTC [13381] ERROR   Program terminated abnormally, see stack trace below for more information
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 730, in _run_task
    output_files = task.run()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 242, in run
    self.output_files = self._run(input_files)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 493, in _run
    process = self._start_diagnostic_script(cmd, env)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 449, in _start_diagnostic_script
    process = subprocess.Popen(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/stef/s/warming_stripes.py'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 407, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 98, in process_recipe
    recipe.run()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 1358, in run
    run_tasks(self.tasks,
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 650, in run_tasks
    _run_tasks_parallel(tasks, max_parallel_tasks)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 695, in _run_tasks_parallel
    _copy_results(task, running[task])
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 718, in _copy_results
    task.output_files, updated_products = future.get()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 730, in _run_task
    output_files = task.run()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 242, in run
    self.output_files = self._run(input_files)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 493, in _run
    process = self._start_diagnostic_script(cmd, env)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 449, in _start_diagnostic_script
    process = subprocess.Popen(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/stef/s/warming_stripes.py'
</pre>
</details>

**Comment by stefsmeets** [comment]
Doing a little bit more digging, it seems that the interpreter is not being added to the `cmd`.

**Comment by stefsmeets** [comment]
It seems that diagnostic scripts get fast-tracked if they are executable, which leads to this error on my system. In addition a bunch of checks are bypassed. What is the reason for this?

https://github.com/ESMValGroup/ESMValCore/blob/208b2af5aa3ba6adc6525a68bc222c9ff01c1327/esmvalcore/_task.py#L293

**Comment by valeriupredoi** [comment]
just add a shebang line to your diagnostic eg `#!/usr/bin/env python` at top of the diag script, we should probably tell users to do that in the documentation :beer:

**Comment by bouweandela** [comment]
> What is the reason for this?

This allows running diagnostic scripts written in arbitrary languages, so long as they are executable and respect the interface.

> Apparently files on NTFS always have the executable bit set, which is what this depends on.

That depends on the options you use for mounting the filesystem, see e.g. [here](https://askubuntu.com/questions/113733/how-do-i-correctly-mount-a-ntfs-partition-in-etc-fstab).

Maybe we could add a note to the error message saying something like: 'If you are unable to remove the executable bit, add a shebang line, e.g.  #!/usr/bin/env python3` at the top of your diagnostic script?

**Comment by stefsmeets** [comment]
I think there is little I can do with WSL to change how the filesystem is mounted. 😅

**Comment by valeriupredoi** [comment]
well now...you can always refactor GRUB :rofl:
