### ISSUE TITLE
Error message if no dataset is defined for a variable is very unclear

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#843]
```
2020-10-22 08:12:15,832 UTC [48962] INFO    esmvalcore._recipe:1298 Creating preprocessor task cmip5/alb
Traceback (most recent call last):
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/work/bd0854/b309192/soft/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_main.py", line 407, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_main.py", line 94, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_recipe.py", line 71, in read_recipe_file
    return Recipe(raw_recipe,
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_recipe.py", line 951, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_recipe.py", line 1299, in initialize_tasks
    task = _get_preprocessor_task(
  File "/mnt/lustre01/pf/b/b309192/ESMValCore/esmvalcore/_recipe.py", line 882, in _get_preprocessor_task
    variable = variables[0]
IndexError: list index out of range
```
from [this](https://github.com/ESMValGroup/ESMValTool/files/5421974/main_log_debug_recipe_preprocessor_derive_test.txt) log running [this](https://github.com/ESMValGroup/ESMValTool/files/5421990/recipe_preprocessor_derive_test.yml.txt) recipe.

**Comment by valeriupredoi** [comment]
ah! I've seen this and I was like "shiver me timbers, whales ahoy" - basically, had no idea where it came from :grin:

**Comment by valeriupredoi** [comment]
no `dataset` or `additional_dataset` :+1:
