### ISSUE TITLE
Test failure for tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#927]
I am noticing this test failure on multiple platforms including my laptop, Github Actions (see [GA](https://github.com/ESMValGroup/ESMValCore/runs/1651548703?check_suite_focus=true) output for both Python 3.8 and 3.9):
```
______________________________________________________ test_tos_fix_data _______________________________________________________
[gw1] linux -- Python 3.9.1 /home/valeriu/miniconda3/envs/esmvalcore39/bin/python3.9

    def test_tos_fix_data():
        """Test ``fix_data`` for ``tos``."""
        grid_lat = iris.coords.DimCoord(
            [20.0, 40.0],
            bounds=[[10.0, 30.0], [30.0, 50.0]],
            var_name='rlat',
            standard_name='grid_latitude',
        )
        grid_lon = iris.coords.DimCoord(
            [10.0, 20.0, 30.0],
            bounds=[[5.0, 15.0], [15.0, 25.0], [25.0, 35.0]],
            var_name='rlon',
            standard_name='grid_longitude',
        )
        latitude = iris.coords.AuxCoord(
            [[-40.0, -20.0, 0.0], [-20.0, 0.0, 20.0]],
            var_name='lat',
            standard_name='latitude',
            units='degrees_north',
        )
        longitude = iris.coords.AuxCoord(
            [[100.0, 140.0, 180.0], [80.0, 100.0, 120.0]],
            var_name='lon',
            standard_name='longitude',
            units='degrees_east',
        )
    
        # Create cube without bounds
        cube = iris.cube.Cube(
            np.full((2, 3), 300.0),
            var_name='tos',
            units='K',
            dim_coords_and_dims=[(grid_lat, 0), (grid_lon, 1)],
            aux_coords_and_dims=[(latitude, (0, 1)), (longitude, (0, 1))],
        )
        assert cube.coord('latitude').bounds is None
        assert cube.coord('longitude').bounds is None
    
        # Apply fix
        fix = Tos(None)
        fixed_cube = fix.fix_data(cube)
        assert fixed_cube is cube
        assert fixed_cube.coord('latitude').bounds is not None
        assert fixed_cube.coord('longitude').bounds is not None
        latitude_bounds = np.array([[[-40, -33.75, -23.75, -30.0],
                                     [-33.75, -6.25, 3.75, -23.75],
                                     [-6.25, -1.02418074021670e-14, 10.0, 3.75]],
                                    [[-30.0, -23.75, -13.75, -20.0],
                                     [-23.75, 3.75, 13.75, -13.75],
                                     [3.75, 10.0, 20.0, 13.75]]])
>       np.testing.assert_allclose(fixed_cube.coord('latitude').bounds,
                                   latitude_bounds)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 24 / 24 (100%)
E       Max absolute difference: 3.75
E       Max relative difference: 5.25762448e+13
E        x: array([[[-43.480762, -34.019238, -22.009619, -31.471143],
E               [-34.019238, -10.      ,   2.009619, -22.009619],
E               [-10.      ,  -0.538476,  11.471143,   2.009619]],...
E        y: array([[[-4.000000e+01, -3.375000e+01, -2.375000e+01, -3.000000e+01],
E               [-3.375000e+01, -6.250000e+00,  3.750000e+00, -2.375000e+01],
E               [-6.250000e+00, -1.024181e-14,  1.000000e+01,  3.750000e+00]],...

tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py:82: AssertionError
```
I can fix this asap by throttling the `rtol` value, but it looks to me as the differences are pretty darn big (O(1e1)) so a functional fix may be needed - any ideas @jvegasbsc ? :confused:

**Comment by valeriupredoi** [comment]
OK dug deeper in this - it's `scipy.interpolate.InterpolatedUnivariateSpline` that's causing this - the new `scipy=1.6.0` makes this test fail (older 1.5.3 is not causing the test to fail) - the func [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.InterpolatedUnivariateSpline.html) for the latest stable version doesn't mention any changes - I don't have a feel of how important are the deltas we are noticing between the two versions, can someone provide input on this please? If the deltas are not crazy big then we can simply fix the test, otherwise we need to dig deeper in the issue and possibly raise a bug report to scipy :beer:

**Comment by valeriupredoi** [comment]
frenly ping @jvegasbsc @schlunma - can we address this issue so we can finally relax `scipy`?

**Comment by schlunma** [comment]
If the new values look reasonable, I agree with Klaus that we should just replace the old values of the test with the new ones :+1:

**Comment by valeriupredoi** [comment]
ping people @here for a solution to this, gents :green_apple:

**Comment by schlunma** [comment]
Having a look at it right now

**Comment by schlunma** [comment]
@valeriupredoi I'm having some troubles running all test in the repo. I did a fresh installation in develop mode (with both `main` branches; thus I had to remove the pin to `esmvalcore<2.3`) and tried

- `pytest`: fails with
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --flake8 --mypy --cov=esmvalcore --cov-report=xml:test-reports/coverage.xml --cov-report=html:test-reports/coverage_html --html=test-reports/report.html --numprocesses                                                                
  inifile: /home/manuel/ESMValCore/setup.cfg                                                                                                                                                                                                                                  
  rootdir: /home/manuel/ESMValCore
```

- `python setup.py test`: fails with
```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing ESMValCore.egg-info/PKG-INFO
writing dependency_links to ESMValCore.egg-info/dependency_links.txt
writing entry points to ESMValCore.egg-info/entry_points.txt
writing requirements to ESMValCore.egg-info/requires.txt
writing top-level names to ESMValCore.egg-info/top_level.txt
writing manifest file 'ESMValCore.egg-info/SOURCES.txt'
running build_ext
/home/manuel/ESMValCore/esmvalcore/experimental/_warnings.py:13: UserWarning: 
  Thank you for trying out the new ESMValCore API.
  Note that this API is experimental and may be subject to change.
  More info: https://github.com/ESMValGroup/ESMValCore/issues/498
/home/manuel/ESMValCore/esmvalcore/experimental/config/_config_validators.py:256: ESMValToolDeprecationWarning: `write_plots` will be removed in 2.4.0.
/home/manuel/ESMValCore/esmvalcore/experimental/config/_config_validators.py:257: ESMValToolDeprecationWarning: `write_netcdf` will be removed in 2.4.0.
/home/manuel/ESMValCore/esmvalcore/experimental/config/_validated_config.py:83: MissingConfigParameter: `drs` is not defined (https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html)
/home/manuel/ESMValCore/esmvalcore/experimental/config/_validated_config.py:83: MissingConfigParameter: `rootpath` is not defined (https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html)
Traceback (most recent call last):
  File "/home/manuel/ESMValCore/setup.py", line 182, in <module>
    setup(
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 256, in run_tests
    test = unittest.main(
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/manuel/ESMValCore/tests/integration/cmor/_fixes/cmip5/test_miroc5.py", line 36, in <module>
    @unittest.mock.patch(
  File "/home/manuel/miniconda3/envs/esm/lib/python3.9/unittest/__init__.py", line 95, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'unittest' has no attribute 'mock'
```

What is the desired way of invoking all tests? Should I raise issues for the fails above or are these expected fails since I did something wrong?

**Comment by zklaus** [comment]
Did you install esmvalcore using `pip install -e .[develop]`?

**Comment by schlunma** [comment]
Yes, I did!

Just reran the entire installation - now `pytest` is working but `python setup.py test` still fails with the error above. No idea what went wrong in the first place. I can work with that, but is the failing of `python setup.py test` something that should be expected? In particular since it says `Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox`?

**Comment by valeriupredoi** [comment]
yeah was about to say `python setup.py test` is ye olde. I've not run it since before the pandemic, I believe we gradually removed testing facilities for it and upgraded all packages and functionality to work with `pytest`. But good catch, we should just remove it from the test instructions and be done with it :+1:

**Comment by valeriupredoi** [comment]
also note that `python setup.py test` runs about half the tests pytest runs
